/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.panelcomponent;

import java.awt.CardLayout;
import projectpkl55.KuesionerPKL;

/**
 *
 * @author _muh.shamad
 */
public class EntryKuesPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntryKues
     */
    public EntryKuesPanel() {
        initComponents();
        init();
    }

    public final void init() {
        section11.setParent(mainPanel2);
        section21.setParent(mainPanel2);
        section31.setParent(mainPanel2);
        section11.setErrorList(errorList1);
        section21.setErrorList(errorList1);
        section31.setErrorList(errorList1);
        section11.addToView();
        section21.addToView();
        section31.addToView();
        ((CardLayout)mainPanel2.getLayout()).show(mainPanel2, "card2");
    }

    public void setMainPanel() {
        KuesionerPKL.kuesioner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryKuesBg1 = new pkl55.background.EntryKuesBg();
        logout21 = new pkl55.component2.Logout2();
        save1 = new pkl55.component2.Save();
        ds21 = new pkl55.component2.Ds2();
        next1 = new pkl55.component2.Next();
        prev1 = new pkl55.component2.Prev();
        jLabel1 = new javax.swing.JLabel();
        timeLabel1 = new pkl55.panel2.TimeLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        errorList1 = new View.ErrorList();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorDetil1 = new View.ErrorDetil();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainPanel2 = new View.SectionPane.MainPanel();
        section21 = new View.SectionPane.Section2();
        section31 = new View.SectionPane.Section3();
        section11 = new View.SectionPane.Section1();

        logout21.setText("");

        save1.setText("");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        ds21.setText("");

        next1.setText("");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });

        prev1.setText("");
        prev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABDURRAHMAN IZZI");

        timeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 17)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kuesioner :");

        jScrollPane1.setViewportView(errorList1);

        jScrollPane2.setViewportView(errorDetil1);

        mainPanel2.add(section21, "card3");
        mainPanel2.add(section31, "card4");
        mainPanel2.add(section11, "card2");

        jScrollPane3.setViewportView(mainPanel2);

        javax.swing.GroupLayout entryKuesBg1Layout = new javax.swing.GroupLayout(entryKuesBg1);
        entryKuesBg1.setLayout(entryKuesBg1Layout);
        entryKuesBg1Layout.setHorizontalGroup(
            entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryKuesBg1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(144, 144, 144)
                .addComponent(prev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(entryKuesBg1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(timeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, entryKuesBg1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(next1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(533, 533, 533)
                        .addComponent(ds21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(logout21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))))
            .addGroup(entryKuesBg1Layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryKuesBg1Layout.createSequentialGroup()
                    .addContainerGap(492, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        entryKuesBg1Layout.setVerticalGroup(
            entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryKuesBg1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryKuesBg1Layout.createSequentialGroup()
                        .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ds21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryKuesBg1Layout.createSequentialGroup()
                        .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(next1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(entryKuesBg1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(entryKuesBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryKuesBg1Layout.createSequentialGroup()
                    .addContainerGap(165, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryKuesBg1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryKuesBg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        Model.Model.saveAll();
    }//GEN-LAST:event_save1ActionPerformed

    private void prev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev1ActionPerformed
        mainPanel2.back();
    }//GEN-LAST:event_prev1ActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        mainPanel2.next();
    }//GEN-LAST:event_next1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.component2.Ds2 ds21;
    private pkl55.background.EntryKuesBg entryKuesBg1;
    private View.ErrorDetil errorDetil1;
    private View.ErrorList errorList1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private pkl55.component2.Logout2 logout21;
    private View.SectionPane.MainPanel mainPanel2;
    private pkl55.component2.Next next1;
    private pkl55.component2.Prev prev1;
    private pkl55.component2.Save save1;
    private View.SectionPane.Section1 section11;
    private View.SectionPane.Section2 section21;
    private View.SectionPane.Section3 section31;
    private pkl55.panel2.TimeLabel timeLabel1;
    // End of variables declaration//GEN-END:variables

    public pkl55.component2.Ds2 getDs21() {
        return ds21;
    }

    public void setDs21(pkl55.component2.Ds2 ds21) {
        this.ds21 = ds21;
    }

    public pkl55.background.EntryKuesBg getEntryKuesBg1() {
        return entryKuesBg1;
    }

    public void setEntryKuesBg1(pkl55.background.EntryKuesBg entryKuesBg1) {
        this.entryKuesBg1 = entryKuesBg1;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

//    public javax.swing.JLabel getjLabel2() {
//        return jLabel2;
//    }
//
//    public void setjLabel2(javax.swing.JLabel jLabel2) {
//        this.jLabel2 = jLabel2;
//    }

    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public pkl55.component2.Logout2 getLogout21() {
        return logout21;
    }

    public void setLogout21(pkl55.component2.Logout2 logout21) {
        this.logout21 = logout21;
    }

    public pkl55.component2.Next getNext1() {
        return next1;
    }

    public void setNext1(pkl55.component2.Next next1) {
        this.next1 = next1;
    }

    public pkl55.component2.Prev getPrev1() {
        return prev1;
    }

    public void setPrev1(pkl55.component2.Prev prev1) {
        this.prev1 = prev1;
    }

    public pkl55.component2.Save getSave1() {
        return save1;
    }

    public void setSave1(pkl55.component2.Save save1) {
        this.save1 = save1;
    }

    public pkl55.panel2.TimeLabel getTimeLabel1() {
        return timeLabel1;
    }

    public void setTimeLabel1(pkl55.panel2.TimeLabel timeLabel1) {
        this.timeLabel1 = timeLabel1;
    }
}
