/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import java.awt.CardLayout;
import pkl55.data.view.Panel;

/**
 *
 * @author faqih_
 */
public class LUMainPanel extends Panel {

    /**
     * Creates new form LUMainPanel
     */
    public LUMainPanel() {
        pkl55.data.view.View.init(23);
        initComponents();
        ((CardLayout)getLayout()).show(this, "card4");
    }

    @Override
    public void init() {
        addToView(lUHal11,lUHal21);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lUHal11 = new pkl55.kuesioner.view.LUHal1();
        jScrollPane2 = new javax.swing.JScrollPane();
        lUHal21 = new pkl55.kuesioner.view.LUHal2();

        setLayout(new java.awt.CardLayout());

        jScrollPane1.setViewportView(lUHal11);

        add(jScrollPane1, "card4");

        jScrollPane2.setViewportView(lUHal21);

        add(jScrollPane2, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private pkl55.kuesioner.view.LUHal1 lUHal11;
    private pkl55.kuesioner.view.LUHal2 lUHal21;
    // End of variables declaration//GEN-END:variables
}
