/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import pkl55.data.view.Hal;

/**
 *
 * @author Zahirah
 */
public class RHal8 extends Hal {

    /**
     * Creates new form section8
     */
    public RHal8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b6r1 = new pkl55.data.view.InputTextField();
        b6r2 = new pkl55.data.view.InputTextField();
        b6r3 = new pkl55.data.view.InputTextField();
        b6r4 = new pkl55.data.view.InputTextField();
        b6r5 = new pkl55.data.view.InputTextField();
        b6r6 = new pkl55.data.view.InputTextField();
        b6r7 = new pkl55.data.view.InputTextField();
        b6r8 = new pkl55.data.view.InputTextField();
        b6r9s2 = new pkl55.data.view.InputTextField();
        b6r9s1 = new pkl55.data.view.InputTextField();
        b6r10 = new pkl55.data.view.InputTextField();
        b6r11s1 = new pkl55.data.view.InputTextField();
        b6r11s2 = new pkl55.data.view.InputTextField();
        b6r12 = new pkl55.data.view.InputTextField();
        b6r13s1 = new pkl55.data.view.InputTextField();
        b6r13s2 = new pkl55.data.view.InputTextField();
        b6r13s3 = new pkl55.data.view.InputTextField();
        b6r14s1 = new pkl55.data.view.InputTextField();
        b6r14s2 = new pkl55.data.view.InputTextField();
        b6r15 = new pkl55.data.view.InputTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatan = new pkl55.data.view.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b6r1.setErrorlist(errorList);
        b6r1.setNextFocusableComponent(b6r2);
        b6r1.setPanel(this);
        b6r1.setPosition(84);
        b6r1.setVarName("b6r1");
        b6r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r1ActionPerformed(evt);
            }
        });
        add(b6r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 30, 30));

        b6r2.setErrorlist(errorList);
        b6r2.setNextFocusableComponent(b6r3);
        b6r2.setPosition(85);
        b6r2.setVarName("b6r2");
        b6r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r2ActionPerformed(evt);
            }
        });
        add(b6r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 30, 30));
        b6r2.setPanel(this);

        b6r3.setErrorlist(errorList);
        b6r3.setNextFocusableComponent(b6r4);
        b6r3.setPosition(86);
        b6r3.setVarName("b6r3");
        b6r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r3ActionPerformed(evt);
            }
        });
        add(b6r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 30, 30));
        b6r3.setPanel(this);

        b6r4.setErrorlist(errorList);
        b6r4.setNextFocusableComponent(b6r5);
        b6r4.setPosition(87);
        b6r4.setVarName("b6r4");
        b6r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r4ActionPerformed(evt);
            }
        });
        add(b6r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 262, 30, 30));
        b6r4.setPanel(this);

        b6r5.setErrorlist(errorList);
        b6r5.setNextFocusableComponent(b6r6);
        b6r5.setPosition(88);
        b6r5.setVarName("b6r5");
        b6r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r5ActionPerformed(evt);
            }
        });
        add(b6r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 332, 30, 30));
        b6r5.setPanel(this);

        b6r6.setErrorlist(errorList);
        b6r6.setNextFocusableComponent(b6r7);
        b6r6.setPosition(89);
        b6r6.setVarName("b6r6");
        b6r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r6ActionPerformed(evt);
            }
        });
        add(b6r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 392, 30, 30));
        b6r6.setPanel(this);

        b6r7.setErrorlist(errorList);
        b6r7.setNextFocusableComponent(b6r8);
        b6r7.setPosition(90);
        b6r7.setVarName("b6r7");
        b6r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r7ActionPerformed(evt);
            }
        });
        add(b6r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 450, 30, 30));
        b6r7.setPanel(this);

        b6r8.setErrorlist(errorList);
        b6r8.setNextFocusableComponent(b6r9s1);
        b6r8.setPosition(91);
        b6r8.setVarName("b6r8");
        b6r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r8ActionPerformed(evt);
            }
        });
        add(b6r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 110, 27));
        b6r8.setPanel(this);

        b6r9s2.setErrorlist(errorList);
        b6r9s2.setNextFocusableComponent(b6r10);
        b6r9s2.setPosition(93);
        b6r9s2.setVarName("b6r9s2");
        b6r9s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r9s2ActionPerformed(evt);
            }
        });
        add(b6r9s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 682, 30, 30));
        b6r9s2.setPanel(this);

        b6r9s1.setErrorlist(errorList);
        b6r9s1.setNextFocusableComponent(b6r9s2);
        b6r9s1.setPosition(92);
        b6r9s1.setVarName("b6r9s1");
        b6r9s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r9s1ActionPerformed(evt);
            }
        });
        add(b6r9s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 30, 30));
        b6r9s1.setPanel(this);

        b6r10.setErrorlist(errorList);
        b6r10.setNextFocusableComponent(b6r11s1);
        b6r10.setPosition(94);
        b6r10.setVarName("b6r10");
        b6r10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r10ActionPerformed(evt);
            }
        });
        add(b6r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 740, 30, 30));
        b6r10.setPanel(this);

        b6r11s1.setErrorlist(errorList);
        b6r11s1.setNextFocusableComponent(b6r11s2);
        b6r11s1.setPosition(95);
        b6r11s1.setVarName("b6r11s1");
        b6r11s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r11s1ActionPerformed(evt);
            }
        });
        add(b6r11s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 30, 30));
        b6r11s1.setPanel(this);

        b6r11s2.setErrorlist(errorList);
        b6r11s2.setNextFocusableComponent(b6r12);
        b6r11s2.setPosition(96);
        b6r11s2.setVarName("b6r11s2");
        b6r11s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r11s2ActionPerformed(evt);
            }
        });
        add(b6r11s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 148, 50, 30));
        b6r11s2.setPanel(this);

        b6r12.setErrorlist(errorList);
        b6r12.setNextFocusableComponent(b6r13s1);
        b6r12.setPosition(97);
        b6r12.setVarName("b6r12s1");
        b6r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r12ActionPerformed(evt);
            }
        });
        add(b6r12, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 263, 50, 30));
        b6r12.setPanel(this);

        b6r13s1.setErrorlist(errorList);
        b6r13s1.setNextFocusableComponent(b6r13s2);
        b6r13s1.setPosition(98);
        b6r13s1.setVarName("b6r13s1");
        b6r13s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r13s1ActionPerformed(evt);
            }
        });
        add(b6r13s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 342, 40, 30));
        b6r13s1.setPanel(this);

        b6r13s2.setErrorlist(errorList);
        b6r13s2.setNextFocusableComponent(b6r13s3);
        b6r13s2.setPosition(99);
        b6r13s2.setVarName("b6r13s2");
        b6r13s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r13s2ActionPerformed(evt);
            }
        });
        add(b6r13s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 398, 40, 30));
        b6r13s2.setPanel(this);

        b6r13s3.setErrorlist(errorList);
        b6r13s3.setNextFocusableComponent(b6r14s1);
        b6r13s3.setPosition(100);
        b6r13s3.setVarName("b6r13s3");
        b6r13s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r13s3ActionPerformed(evt);
            }
        });
        add(b6r13s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 40, 30));
        b6r13s3.setPanel(this);

        b6r14s1.setErrorlist(errorList);
        b6r14s1.setNextFocusableComponent(b6r14s2);
        b6r14s1.setPosition(101);
        b6r14s1.setVarName("b6r14s1");
        b6r14s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r14s1ActionPerformed(evt);
            }
        });
        add(b6r14s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 40, 30));
        b6r14s1.setPanel(this);

        b6r14s2.setErrorlist(errorList);
        b6r14s2.setNextFocusableComponent(b6r15);
        b6r14s2.setPosition(102);
        b6r14s2.setVarName("b6r13s2");
        b6r14s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r14s2ActionPerformed(evt);
            }
        });
        add(b6r14s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 40, 30));
        b6r14s2.setPanel(this);

        b6r15.setErrorlist(errorList);
        b6r15.setPosition(103);
        b6r15.setVarName("b6r15");
        b6r15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6r15ActionPerformed(evt);
            }
        });
        add(b6r15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 700, 40, 30));
        b6r15.setPanel(this);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        catatan.setBorder(null);
        catatan.setColumns(20);
        catatan.setRows(5);
        catatan.setPanel(this);
        catatan.setVarName("catatan");
        jScrollPane1.setViewportView(catatan);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 840, 710, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/R08.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void b6r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r1ActionPerformed

    private void b6r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r2ActionPerformed

    private void b6r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r3ActionPerformed

    private void b6r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r4ActionPerformed

    private void b6r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r5ActionPerformed

    private void b6r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r6ActionPerformed

    private void b6r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r7ActionPerformed

    private void b6r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r8ActionPerformed

    private void b6r10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r10ActionPerformed

    private void b6r9s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r9s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r9s2ActionPerformed

    private void b6r9s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r9s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r9s1ActionPerformed

    private void b6r11s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r11s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r11s1ActionPerformed

    private void b6r11s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r11s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r11s2ActionPerformed

    private void b6r12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r12ActionPerformed

    private void b6r13s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r13s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r13s1ActionPerformed

    private void b6r13s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r13s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r13s2ActionPerformed

    private void b6r13s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r13s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r13s3ActionPerformed

    private void b6r14s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r14s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r14s1ActionPerformed

    private void b6r14s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r14s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r14s2ActionPerformed

    private void b6r15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6r15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6r15ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.data.view.InputTextField b6r1;
    private pkl55.data.view.InputTextField b6r10;
    private pkl55.data.view.InputTextField b6r11s1;
    private pkl55.data.view.InputTextField b6r11s2;
    private pkl55.data.view.InputTextField b6r12;
    private pkl55.data.view.InputTextField b6r13s1;
    private pkl55.data.view.InputTextField b6r13s2;
    private pkl55.data.view.InputTextField b6r13s3;
    private pkl55.data.view.InputTextField b6r14s1;
    private pkl55.data.view.InputTextField b6r14s2;
    private pkl55.data.view.InputTextField b6r15;
    private pkl55.data.view.InputTextField b6r2;
    private pkl55.data.view.InputTextField b6r3;
    private pkl55.data.view.InputTextField b6r4;
    private pkl55.data.view.InputTextField b6r5;
    private pkl55.data.view.InputTextField b6r6;
    private pkl55.data.view.InputTextField b6r7;
    private pkl55.data.view.InputTextField b6r8;
    private pkl55.data.view.InputTextField b6r9s1;
    private pkl55.data.view.InputTextField b6r9s2;
    private pkl55.data.view.TextArea catatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
