/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import pkl55.data.view.ErrorList;
import pkl55.data.view.Hal;

/**
 *
 * @author user
 */
public class RHal2 extends Hal {

    /**
     * Creates new form section2
     */
    public RHal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3r2 = new pkl55.data.view.TextFieldLoop();
        b3r3 = new pkl55.data.view.TextFieldLoop();
        b3r4 = new pkl55.data.view.TextFieldLoop();
        b3r5 = new pkl55.data.view.TextFieldLoop();
        b3r6 = new pkl55.data.view.TextFieldLoop();
        b3r7 = new pkl55.data.view.TextFieldLoop();
        b3r8 = new pkl55.data.view.TextFieldLoop();
        b3r9 = new pkl55.data.view.TextFieldLoop();
        b3r10 = new pkl55.data.view.TextFieldLoop();
        b3r11 = new pkl55.data.view.TextFieldLoop();
        b3r12 = new pkl55.data.view.TextFieldLoop();
        b3r13 = new pkl55.data.view.TextFieldLoop();
        b3r14 = new pkl55.data.view.TextFieldLoop();
        section2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b3r2.setErrorlist(errorList);
        b3r2.setLoopName("b3");
        b3r2.setPanel(this);
        b3r2.setPosition(20);
        b3r2.setStart(true);
        b3r2.setVarName("b3r2");
        add(b3r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 210, -1));

        b3r3.setErrorlist(errorList);
        b3r3.setLoopName("b3");
        b3r3.setPanel(this);
        b3r3.setPosition(21);
        b3r3.setVarName("b3r3");
        add(b3r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 306, 25, 25));

        b3r4.setErrorlist(errorList);
        b3r4.setLoopName("b3");
        b3r4.setPanel(this);
        b3r4.setPosition(22);
        b3r4.setVarName("b3r4");
        add(b3r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 306, 25, 25));

        b3r5.setErrorlist(errorList);
        b3r5.setLoopName("b3");
        b3r5.setPanel(this);
        b3r5.setPosition(23);
        b3r5.setVarName("b3r5");
        b3r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3r5ActionPerformed(evt);
            }
        });
        add(b3r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 306, 51, 25));

        b3r6.setErrorlist(errorList);
        b3r6.setLoopName("b3");
        b3r6.setPanel(this);
        b3r6.setPosition(24);
        b3r6.setVarName("b3r6");
        add(b3r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 306, 25, 25));

        b3r7.setErrorlist(errorList);
        b3r7.setLoopName("b3");
        b3r7.setPanel(this);
        b3r7.setPosition(25);
        b3r7.setVarName("b3r7");
        add(b3r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 306, 25, 25));

        b3r8.setErrorlist(errorList);
        b3r8.setLoopName("b3");
        b3r8.setPanel(this);
        b3r8.setPosition(26);
        b3r8.setVarName("b3r8");
        add(b3r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 306, 51, 25));

        b3r9.setErrorlist(errorList);
        b3r9.setLoopName("b3");
        b3r9.setPanel(this);
        b3r9.setPosition(27);
        b3r9.setVarName("b3r9");
        add(b3r9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 306, 25, 25));

        b3r10.setErrorlist(errorList);
        b3r10.setLoopName("b3");
        b3r10.setPanel(this);
        b3r10.setPosition(28);
        b3r10.setVarName("b3r10");
        add(b3r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 306, 25, 25));

        b3r11.setErrorlist(errorList);
        b3r11.setLoopName("b3");
        b3r11.setPanel(this);
        b3r11.setPosition(29);
        b3r11.setVarName("b3r11");
        add(b3r11, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 306, 25, 25));

        b3r12.setErrorlist(errorList);
        b3r12.setLoopName("b3");
        b3r12.setPanel(this);
        b3r12.setPosition(30);
        b3r12.setVarName("b3r12");
        add(b3r12, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 306, 25, 25));

        b3r13.setErrorlist(errorList);
        b3r13.setLoopName("b3");
        b3r13.setPanel(this);
        b3r13.setPosition(31);
        b3r13.setVarName("b3r13");
        add(b3r13, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 306, 25, 25));

        b3r14.setErrorlist(errorList);
        b3r14.setLoopName("b3");
        b3r14.setNextpage(true);
        b3r14.setPanel(this);
        b3r14.setPosition(32);
        b3r14.setVarName("b3r14");
        add(b3r14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 306, 25, 25));

        section2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/R02.png"))); // NOI18N
        add(section2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1070));
    }// </editor-fold>//GEN-END:initComponents

    private void b3r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3r5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3r5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.data.view.TextFieldLoop b3r10;
    private pkl55.data.view.TextFieldLoop b3r11;
    private pkl55.data.view.TextFieldLoop b3r12;
    private pkl55.data.view.TextFieldLoop b3r13;
    private pkl55.data.view.TextFieldLoop b3r14;
    private pkl55.data.view.TextFieldLoop b3r2;
    private pkl55.data.view.TextFieldLoop b3r3;
    private pkl55.data.view.TextFieldLoop b3r4;
    private pkl55.data.view.TextFieldLoop b3r5;
    private pkl55.data.view.TextFieldLoop b3r6;
    private pkl55.data.view.TextFieldLoop b3r7;
    private pkl55.data.view.TextFieldLoop b3r8;
    private pkl55.data.view.TextFieldLoop b3r9;
    private javax.swing.JLabel section2;
    // End of variables declaration//GEN-END:variables
}
