/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import pkl55.data.view.Hal;

/**
 *
 * @author Zahirah
 */
public class RHal6 extends Hal {

    /**
     * Creates new form section6
     */
    public RHal6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b4r1 = new pkl55.data.view.TextField();
        b4ar1 = new pkl55.data.view.InputTextField();
        b4ar2 = new pkl55.data.view.InputTextField();
        b4ar3 = new pkl55.data.view.InputTextField();
        b4ar4 = new pkl55.data.view.InputTextField();
        b4ar5 = new pkl55.data.view.InputTextField();
        b4ar6 = new pkl55.data.view.InputTextField();
        b4ar7 = new pkl55.data.view.InputTextField();
        b4ar8 = new pkl55.data.view.InputTextField();
        b4ar9 = new pkl55.data.view.InputTextField();
        b4ar10 = new pkl55.data.view.InputTextField();
        b4ar11 = new pkl55.data.view.InputTextField();
        b4ar12 = new pkl55.data.view.InputTextField();
        b4ar13 = new pkl55.data.view.InputTextField();
        b4ar14 = new pkl55.data.view.InputTextField();
        b4ar15 = new pkl55.data.view.InputTextField();
        b4ar16 = new pkl55.data.view.InputTextField();
        b4br17 = new pkl55.data.view.InputTextField();
        b4br18 = new pkl55.data.view.InputTextField();
        b4br19 = new pkl55.data.view.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b4r1.setErrorlist(errorList);
        b4r1.setNextFocusableComponent(b4ar1);
        b4r1.setPanel(this);
        b4r1.setPosition(49);
        b4r1.setVarName("b4r1");
        b4r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4r1ActionPerformed(evt);
            }
        });
        add(b4r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 50, 25));

        b4ar1.setErrorlist(errorList);
        b4ar1.setPanel(this);
        b4ar1.setPosition(50);
        b4ar1.setVarName("b4ar1");
        b4ar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar1ActionPerformed(evt);
            }
        });
        add(b4ar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 252, 24, 24));

        b4ar2.setErrorlist(errorList);
        b4ar2.setNextFocusableComponent(b4ar3);
        b4ar2.setPanel(this);
        b4ar2.setPosition(51);
        b4ar2.setVarName("b4ar2");
        b4ar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar2ActionPerformed(evt);
            }
        });
        add(b4ar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 288, 24, 24));

        b4ar3.setErrorlist(errorList);
        b4ar3.setNextFocusableComponent(b4ar4);
        b4ar3.setPanel(this);
        b4ar3.setPosition(52);
        b4ar3.setVarName("b4ar3");
        b4ar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar3ActionPerformed(evt);
            }
        });
        add(b4ar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 24, 24));

        b4ar4.setErrorlist(errorList);
        b4ar4.setNextFocusableComponent(b4ar5);
        b4ar4.setPanel(this);
        b4ar4.setPosition(53);
        b4ar4.setVarName("b4ar4");
        b4ar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar4ActionPerformed(evt);
            }
        });
        add(b4ar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 352, 24, 24));

        b4ar5.setErrorlist(errorList);
        b4ar5.setNextFocusableComponent(b4ar6);
        b4ar5.setPanel(this);
        b4ar5.setPosition(54);
        b4ar5.setVarName("b4ar5");
        b4ar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar5ActionPerformed(evt);
            }
        });
        add(b4ar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 384, 24, 24));

        b4ar6.setErrorlist(null);
        b4ar6.setNextFocusableComponent(b4ar7);
        b4ar6.setPanel(this);
        b4ar6.setPosition(55);
        b4ar6.setVarName("b4ar6");
        b4ar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar6ActionPerformed(evt);
            }
        });
        add(b4ar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 418, 24, 24));

        b4ar7.setErrorlist(errorList);
        b4ar7.setNextFocusableComponent(b4ar8);
        b4ar7.setPanel(this);
        b4ar7.setPosition(56);
        b4ar7.setVarName("b4ar7");
        b4ar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar7ActionPerformed(evt);
            }
        });
        add(b4ar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 456, 24, 24));

        b4ar8.setErrorlist(errorList);
        b4ar8.setNextFocusableComponent(b4ar9);
        b4ar8.setPanel(this);
        b4ar8.setPosition(57);
        b4ar8.setVarName("b4ar8");
        b4ar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar8ActionPerformed(evt);
            }
        });
        add(b4ar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 502, 24, 24));

        b4ar9.setErrorlist(errorList);
        b4ar9.setNextFocusableComponent(b4ar10);
        b4ar9.setPanel(this);
        b4ar9.setPosition(58);
        b4ar9.setVarName("b4ar9");
        b4ar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar9ActionPerformed(evt);
            }
        });
        add(b4ar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 542, 24, 24));

        b4ar10.setErrorlist(null);
        b4ar10.setNextFocusableComponent(b4ar11);
        b4ar10.setPanel(this);
        b4ar10.setPosition(59);
        b4ar10.setVarName("b4ar10");
        b4ar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar10ActionPerformed(evt);
            }
        });
        add(b4ar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 585, 24, 24));

        b4ar11.setErrorlist(errorList);
        b4ar11.setNextFocusableComponent(b4ar12);
        b4ar11.setPanel(this);
        b4ar11.setPosition(60);
        b4ar11.setVarName("b4ar11");
        b4ar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar11ActionPerformed(evt);
            }
        });
        add(b4ar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 24, 24));

        b4ar12.setErrorlist(null);
        b4ar12.setNextFocusableComponent(b4ar13);
        b4ar12.setPanel(this);
        b4ar12.setPosition(61);
        b4ar12.setVarName("b4ar12");
        b4ar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar12ActionPerformed(evt);
            }
        });
        add(b4ar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 652, 24, 24));

        b4ar13.setEnabled(false);
        b4ar13.setErrorlist(null);
        b4ar13.setNextFocusableComponent(b4ar14);
        b4ar13.setPanel(this);
        b4ar13.setPosition(62);
        b4ar13.setVarName("b4ar13");
        b4ar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar13ActionPerformed(evt);
            }
        });
        add(b4ar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 688, 24, 24));
        b4ar13.getAccessibleContext().setAccessibleName("");

        b4ar14.setErrorlist(null);
        b4ar14.setNextFocusableComponent(b4ar15);
        b4ar14.setPanel(this);
        b4ar14.setPosition(63);
        b4ar14.setVarName("b4ar14");
        b4ar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar14ActionPerformed(evt);
            }
        });
        add(b4ar14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 718, 24, 24));

        b4ar15.setErrorlist(null);
        b4ar15.setNextFocusableComponent(b4ar16);
        b4ar15.setPanel(this);
        b4ar15.setPosition(64);
        b4ar15.setVarName("b4ar15");
        b4ar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar15ActionPerformed(evt);
            }
        });
        add(b4ar15, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 752, 24, 24));

        b4ar16.setErrorlist(errorList);
        b4ar16.setNextFocusableComponent(b4br17);
        b4ar16.setPanel(this);
        b4ar16.setPosition(65);
        b4ar16.setVarName("b4ar16");
        b4ar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ar16ActionPerformed(evt);
            }
        });
        add(b4ar16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 788, 24, 24));

        b4br17.setErrorlist(null);
        b4br17.setNextFocusableComponent(b4br18);
        b4br17.setPanel(this);
        b4br17.setPosition(66);
        b4br17.setVarName("b4br17");
        b4br17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br17ActionPerformed(evt);
            }
        });
        add(b4br17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 923, 24, 24));

        b4br18.setErrorlist(null);
        b4br18.setNextFocusableComponent(b4br19);
        b4br18.setPanel(this);
        b4br18.setPosition(67);
        b4br18.setVarName("b4br18");
        b4br18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br18ActionPerformed(evt);
            }
        });
        add(b4br18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 955, 24, 24));

        b4br19.setErrorlist(null);
        b4br19.setNextpage(true);
        b4br19.setPanel(this);
        b4br19.setPosition(68);
        b4br19.setVarName("b4br19");
        b4br19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br19ActionPerformed(evt);
            }
        });
        add(b4br19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 990, 24, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/R06.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1070));
    }// </editor-fold>//GEN-END:initComponents

    private void b4ar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar1ActionPerformed

    private void b4ar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar2ActionPerformed

    private void b4ar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar3ActionPerformed

    private void b4ar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar4ActionPerformed

    private void b4ar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar5ActionPerformed

    private void b4ar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar6ActionPerformed

    private void b4ar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar7ActionPerformed

    private void b4ar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar8ActionPerformed

    private void b4ar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar9ActionPerformed

    private void b4ar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar10ActionPerformed

    private void b4ar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar11ActionPerformed

    private void b4ar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar12ActionPerformed

    private void b4ar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar13ActionPerformed

    private void b4ar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar14ActionPerformed

    private void b4ar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar15ActionPerformed

    private void b4ar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ar16ActionPerformed

    private void b4br17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br17ActionPerformed

    private void b4br18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br18ActionPerformed

    private void b4br19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br19ActionPerformed

    private void b4r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4r1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.data.view.InputTextField b4ar1;
    private pkl55.data.view.InputTextField b4ar10;
    private pkl55.data.view.InputTextField b4ar11;
    private pkl55.data.view.InputTextField b4ar12;
    private pkl55.data.view.InputTextField b4ar13;
    private pkl55.data.view.InputTextField b4ar14;
    private pkl55.data.view.InputTextField b4ar15;
    private pkl55.data.view.InputTextField b4ar16;
    private pkl55.data.view.InputTextField b4ar2;
    private pkl55.data.view.InputTextField b4ar3;
    private pkl55.data.view.InputTextField b4ar4;
    private pkl55.data.view.InputTextField b4ar5;
    private pkl55.data.view.InputTextField b4ar6;
    private pkl55.data.view.InputTextField b4ar7;
    private pkl55.data.view.InputTextField b4ar8;
    private pkl55.data.view.InputTextField b4ar9;
    private pkl55.data.view.InputTextField b4br17;
    private pkl55.data.view.InputTextField b4br18;
    private pkl55.data.view.InputTextField b4br19;
    private pkl55.data.view.TextField b4r1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void pack() {
        
    }
}
