/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import pkl55.data.view.Hal;

/**
 *
 * @author Zahirah
 */
public class RHal7 extends Hal {

    /**
     * Creates new form section7
     */
    public RHal7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b5r2 = new pkl55.data.view.InputTextField();
        b5r1 = new pkl55.data.view.InputTextField();
        b4cr32 = new pkl55.data.view.InputTextField();
        b4cr31 = new pkl55.data.view.InputTextField();
        b4cr30 = new pkl55.data.view.InputTextField();
        b4cr29 = new pkl55.data.view.InputTextField();
        b4cr28 = new pkl55.data.view.InputTextField();
        b4cr27 = new pkl55.data.view.InputTextField();
        b4cr26 = new pkl55.data.view.InputTextField();
        b4cr25 = new pkl55.data.view.InputTextField();
        b4br24 = new pkl55.data.view.InputTextField();
        b4br23 = new pkl55.data.view.InputTextField();
        b4br22 = new pkl55.data.view.InputTextField();
        b4br21 = new pkl55.data.view.InputTextField();
        b4br20 = new pkl55.data.view.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b5r2.setErrorlist(errorList);
        b5r2.setNextpage(true);
        b5r2.setPanel(this);
        b5r2.setPosition(83);
        b5r2.setVarName("b5r2");
        b5r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r2ActionPerformed(evt);
            }
        });
        add(b5r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 963, 24, 24));

        b5r1.setErrorlist(errorList);
        b5r1.setNextFocusableComponent(b5r2);
        b5r1.setPanel(this);
        b5r1.setPosition(82);
        b5r1.setVarName("b5r1");
        b5r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r1ActionPerformed(evt);
            }
        });
        add(b5r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 842, 24, 24));

        b4cr32.setErrorlist(errorList);
        b4cr32.setNextFocusableComponent(b5r1);
        b4cr32.setPanel(this);
        b4cr32.setPosition(81);
        b4cr32.setVarName("b4cr32");
        b4cr32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr32ActionPerformed(evt);
            }
        });
        add(b4cr32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, 20, -1));

        b4cr31.setErrorlist(errorList);
        b4cr31.setNextFocusableComponent(b4cr32);
        b4cr31.setPanel(this);
        b4cr31.setPosition(80);
        b4cr31.setVarName("b4cr31");
        b4cr31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr31ActionPerformed(evt);
            }
        });
        add(b4cr31, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 636, 20, -1));

        b4cr30.setErrorlist(errorList);
        b4cr30.setNextFocusableComponent(b4cr31);
        b4cr30.setPanel(this);
        b4cr30.setPosition(79);
        b4cr30.setVarName("b4cr30");
        b4cr30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr30ActionPerformed(evt);
            }
        });
        add(b4cr30, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 602, 20, -1));

        b4cr29.setErrorlist(errorList);
        b4cr29.setNextFocusableComponent(b4cr30);
        b4cr29.setPanel(this);
        b4cr29.setPosition(78);
        b4cr29.setVarName("b4cr29");
        b4cr29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr29ActionPerformed(evt);
            }
        });
        add(b4cr29, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 568, 20, -1));

        b4cr28.setErrorlist(errorList);
        b4cr28.setNextFocusableComponent(b4cr29);
        b4cr28.setPanel(this);
        b4cr28.setPosition(77);
        b4cr28.setVarName("b4cr28");
        b4cr28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr28ActionPerformed(evt);
            }
        });
        add(b4cr28, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 534, 20, -1));

        b4cr27.setErrorlist(errorList);
        b4cr27.setNextFocusableComponent(b4cr28);
        b4cr27.setPanel(this);
        b4cr27.setPosition(76);
        b4cr27.setVarName("b4cr27");
        b4cr27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr27ActionPerformed(evt);
            }
        });
        add(b4cr27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 502, 20, -1));

        b4cr26.setErrorlist(errorList);
        b4cr26.setNextFocusableComponent(b4cr27);
        b4cr26.setPanel(this);
        b4cr26.setPosition(75);
        b4cr26.setVarName("b4cr26");
        b4cr26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr26ActionPerformed(evt);
            }
        });
        add(b4cr26, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 462, 22, 22));

        b4cr25.setErrorlist(errorList);
        b4cr25.setNextFocusableComponent(b4cr26);
        b4cr25.setPanel(this);
        b4cr25.setPosition(74);
        b4cr25.setVarName("b4cr25");
        b4cr25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4cr25ActionPerformed(evt);
            }
        });
        add(b4cr25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 20, -1));

        b4br24.setErrorlist(errorList);
        b4br24.setNextFocusableComponent(b4cr25);
        b4br24.setPanel(this);
        b4br24.setPosition(73);
        b4br24.setVarName("b4br24");
        b4br24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br24ActionPerformed(evt);
            }
        });
        add(b4br24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 20, -1));

        b4br23.setErrorlist(null);
        b4br23.setNextFocusableComponent(b4br24);
        b4br23.setPanel(this);
        b4br23.setPosition(72);
        b4br23.setVarName("b4br23");
        b4br23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br23ActionPerformed(evt);
            }
        });
        add(b4br23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 257, 22, 22));

        b4br22.setErrorlist(null);
        b4br22.setNextFocusableComponent(b4br23);
        b4br22.setPanel(this);
        b4br22.setPosition(71);
        b4br22.setVarName("b4br22");
        b4br22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br22ActionPerformed(evt);
            }
        });
        add(b4br22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 222, 22, 22));

        b4br21.setErrorlist(errorList);
        b4br21.setNextFocusableComponent(b4br22);
        b4br21.setPanel(this);
        b4br21.setPosition(70);
        b4br21.setVarName("b4br21");
        b4br21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br21ActionPerformed(evt);
            }
        });
        add(b4br21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 20, -1));

        b4br20.setErrorlist(errorList);
        b4br20.setNextFocusableComponent(b4br21);
        b4br20.setPanel(this);
        b4br20.setPosition(69);
        b4br20.setVarName("b4br20");
        b4br20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4br20ActionPerformed(evt);
            }
        });
        add(b4br20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 22, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/R07.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void b4br20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br20ActionPerformed

    private void b4br21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br21ActionPerformed

    private void b4br22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br22ActionPerformed

    private void b4br23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br23ActionPerformed

    private void b4br24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4br24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4br24ActionPerformed

    private void b4cr25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr25ActionPerformed

    private void b4cr26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr26ActionPerformed

    private void b4cr27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr27ActionPerformed

    private void b4cr28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr28ActionPerformed

    private void b4cr29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr29ActionPerformed

    private void b4cr30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr30ActionPerformed

    private void b4cr31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr31ActionPerformed

    private void b4cr32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4cr32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4cr32ActionPerformed

    private void b5r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r1ActionPerformed

    private void b5r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.data.view.InputTextField b4br20;
    private pkl55.data.view.InputTextField b4br21;
    private pkl55.data.view.InputTextField b4br22;
    private pkl55.data.view.InputTextField b4br23;
    private pkl55.data.view.InputTextField b4br24;
    private pkl55.data.view.InputTextField b4cr25;
    private pkl55.data.view.InputTextField b4cr26;
    private pkl55.data.view.InputTextField b4cr27;
    private pkl55.data.view.InputTextField b4cr28;
    private pkl55.data.view.InputTextField b4cr29;
    private pkl55.data.view.InputTextField b4cr30;
    private pkl55.data.view.InputTextField b4cr31;
    private pkl55.data.view.InputTextField b4cr32;
    private pkl55.data.view.InputTextField b5r1;
    private pkl55.data.view.InputTextField b5r2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
