/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import pkl55.data.view.Panel;

/**
 *
 * @author faqih_
 */
public class RMainPanel extends Panel {

    /**
     * Creates new form RMainPanel
     */
    public RMainPanel() {
        pkl55.data.view.View.init(104);
        initComponents();
    }

    @Override
    public void init() {
        addToView(rHal11,rHal21,rHal31,rHal41,rHal51,rHal61,rHal71,rHal81);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rHal11 = new pkl55.kuesioner.view.RHal1();
        rHal21 = new pkl55.kuesioner.view.RHal2();
        rHal31 = new pkl55.kuesioner.view.RHal3();
        rHal41 = new pkl55.kuesioner.view.RHal4();
        rHal51 = new pkl55.kuesioner.view.RHal5();
        rHal61 = new pkl55.kuesioner.view.RHal6();
        rHal71 = new pkl55.kuesioner.view.RHal7();
        rHal81 = new pkl55.kuesioner.view.RHal8();

        setLayout(new java.awt.CardLayout());
        add(rHal11, "card2");
        add(rHal21, "card3");
        add(rHal31, "card4");
        add(rHal41, "card5");
        add(rHal51, "card6");
        add(rHal61, "card7");
        add(rHal71, "card8");
        add(rHal81, "card9");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.kuesioner.view.RHal1 rHal11;
    private pkl55.kuesioner.view.RHal2 rHal21;
    private pkl55.kuesioner.view.RHal3 rHal31;
    private pkl55.kuesioner.view.RHal4 rHal41;
    private pkl55.kuesioner.view.RHal5 rHal51;
    private pkl55.kuesioner.view.RHal6 rHal61;
    private pkl55.kuesioner.view.RHal7 rHal71;
    private pkl55.kuesioner.view.RHal8 rHal81;
    // End of variables declaration//GEN-END:variables
}
