/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import java.awt.Component;
import pkl55.data.view.Field;
import pkl55.data.view.Hal;
/**
 *
 * @author nurilmi
 */
public class UUHal2 extends Hal{

    /**
     * Creates new form UHal2
     */
    public UUHal2() {
        initComponents();
    }

public void addToView(){
        for (Component comp : getComponents()) {
            if (comp.isVisible()) {
                if (comp instanceof Field) {
                    ((Field) comp).addToView();
                    ((Field) comp).setErrorlist(errorList);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3r1 = new pkl55.data.view.InputTextField();
        b3r2 = new pkl55.data.view.InputTextField();
        b3r3 = new pkl55.data.view.InputTextField();
        b3r4 = new pkl55.data.view.InputTextField();
        b3r5 = new pkl55.data.view.InputTextField();
        b3r6 = new pkl55.data.view.InputTextField();
        b3r7s1 = new pkl55.data.view.InputTextField();
        b3r7s2 = new pkl55.data.view.InputTextField();
        b3r8 = new pkl55.data.view.InputTextField();
        b3r8lainnya = new pkl55.data.view.InputTextField();
        b3r9s1 = new pkl55.data.view.InputTextField();
        b3r9s2 = new pkl55.data.view.InputTextField();
        b3r10 = new pkl55.data.view.InputTextField();
        b3r10lainnya = new pkl55.data.view.InputTextField();
        b3r11s1 = new pkl55.data.view.InputTextField();
        b3r11s2 = new pkl55.data.view.InputTextField();
        b3r12s1 = new pkl55.data.view.InputTextField();
        b3r12s2 = new pkl55.data.view.InputTextField();
        b3r13s1 = new pkl55.data.view.InputTextField();
        b3r13s2 = new pkl55.data.view.InputTextField();
        b3r13s2lainnya = new pkl55.data.view.InputTextField();
        b3r14s1 = new pkl55.data.view.InputTextField();
        b3r14s2 = new pkl55.data.view.InputTextField();
        b3r14s2lainnya = new pkl55.data.view.InputTextField();
        b3r15 = new pkl55.data.view.InputTextField();
        b3r16 = new pkl55.data.view.InputTextField();
        b3r17 = new pkl55.data.view.InputTextField();
        b3r18s1t1 = new pkl55.data.view.InputTextField();
        b3r18s1t2 = new pkl55.data.view.InputTextField();
        b3r18s1t3 = new pkl55.data.view.InputTextField();
        b3r18s1t4 = new pkl55.data.view.InputTextField();
        b3r18s1t5 = new pkl55.data.view.InputTextField();
        b3r18s1t6 = new pkl55.data.view.InputTextField();
        b3r18s2t1 = new pkl55.data.view.InputTextField();
        b3r18s2t2 = new pkl55.data.view.InputTextField();
        b3r18s2t3 = new pkl55.data.view.InputTextField();
        b3r18s2t4 = new pkl55.data.view.InputTextField();
        b3r18s2t5 = new pkl55.data.view.InputTextField();
        b3r18s2t6 = new pkl55.data.view.InputTextField();
        b3r19s1t1 = new pkl55.data.view.InputTextField();
        b3r19s1t2 = new pkl55.data.view.InputTextField();
        b3r19s1t3 = new pkl55.data.view.InputTextField();
        b3r19s1t4 = new pkl55.data.view.InputTextField();
        b3r19s1t5 = new pkl55.data.view.InputTextField();
        b3r19s1t6 = new pkl55.data.view.InputTextField();
        b3r19s2t1 = new pkl55.data.view.InputTextField();
        b3r19s2t2 = new pkl55.data.view.InputTextField();
        b3r19s2t3 = new pkl55.data.view.InputTextField();
        b3r19s2t4 = new pkl55.data.view.InputTextField();
        b3r19s2t5 = new pkl55.data.view.InputTextField();
        b3r19s2t6 = new pkl55.data.view.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(753, 1069));
        setMinimumSize(new java.awt.Dimension(753, 1069));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b3r1.setErrorlist(errorList);
        b3r1.setNextFocusableComponent(b3r2);
        b3r1.setPanel(this);
        b3r1.setPosition(22);
        b3r1.setVarName("b3r1");
        add(b3r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 67, 300, 17));

        b3r2.setErrorlist(errorList);
        b3r2.setNextFocusableComponent(b3r3);
        b3r2.setPanel(this);
        b3r2.setPosition(23);
        b3r2.setVarName("b3r2");
        add(b3r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 88, 45, 24));

        b3r3.setErrorlist(errorList);
        b3r3.setNextFocusableComponent(b3r4);
        b3r3.setPanel(this);
        b3r3.setPosition(24);
        b3r3.setVarName("b3r3");
        add(b3r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 121, 24, 24));

        b3r4.setErrorlist(errorList);
        b3r4.setNextFocusableComponent(b3r5);
        b3r4.setPanel(this);
        b3r4.setPosition(25);
        b3r4.setVarName("b3r4");
        add(b3r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 193, 45, 24));

        b3r5.setErrorlist(errorList);
        b3r5.setNextFocusableComponent(b3r6);
        b3r5.setPanel(this);
        b3r5.setPosition(26);
        b3r5.setVarName("b3r5");
        add(b3r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 269, 24, 24));

        b3r6.setErrorlist(errorList);
        b3r6.setNextFocusableComponent(b3r7s1);
        b3r6.setPanel(this);
        b3r6.setPosition(27);
        b3r6.setVarName("b3r6");
        add(b3r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 316, 24, 24));

        b3r7s1.setErrorlist(errorList);
        b3r7s1.setNextFocusableComponent(b3r7s2);
        b3r7s1.setPanel(this);
        b3r7s1.setPosition(28);
        b3r7s1.setVarName("b3r7s1");
        add(b3r7s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, 70));

        b3r7s2.setErrorlist(errorList);
        b3r7s2.setNextFocusableComponent(b3r8);
        b3r7s2.setPanel(this);
        b3r7s2.setPosition(29);
        b3r7s2.setVarName("b3r7s2");
        add(b3r7s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 397, 109, 24));

        b3r8.setErrorlist(errorList);
        b3r8.setNextFocusableComponent(b3r8lainnya);
        b3r8.setPanel(this);
        b3r8.setPosition(30);
        b3r8.setVarName("b3r8");
        add(b3r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 499, 24, 24));

        b3r8lainnya.setErrorlist(errorList);
        b3r8lainnya.setNextFocusableComponent(b3r9s1);
        b3r8lainnya.setPanel(this);
        b3r8lainnya.setPosition(31);
        b3r8lainnya.setVarName("b3r8lainnya");
        add(b3r8lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 515, 70, -1));

        b3r9s1.setErrorlist(errorList);
        b3r9s1.setNextFocusableComponent(b3r9s2);
        b3r9s1.setPanel(this);
        b3r9s1.setPosition(32);
        b3r9s1.setVarName("b3r9s1");
        add(b3r9s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 567, 24, 24));

        b3r9s2.setErrorlist(errorList);
        b3r9s2.setNextFocusableComponent(b3r10);
        b3r9s2.setPanel(this);
        b3r9s2.setPosition(33);
        b3r9s2.setVarName("b3r9s2");
        add(b3r9s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 618, 24, 24));

        b3r10.setErrorlist(errorList);
        b3r10.setNextFocusableComponent(b3r10lainnya);
        b3r10.setPanel(this);
        b3r10.setPosition(34);
        b3r10.setVarName("b3r10");
        add(b3r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 679, 24, 24));

        b3r10lainnya.setErrorlist(errorList);
        b3r10lainnya.setNextFocusableComponent(b3r11s1);
        b3r10lainnya.setPanel(this);
        b3r10lainnya.setPosition(35);
        b3r10lainnya.setVarName("b3r10lainnya");
        add(b3r10lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 694, 140, 15));

        b3r11s1.setErrorlist(errorList);
        b3r11s1.setNextFocusableComponent(b3r11s2);
        b3r11s1.setPanel(this);
        b3r11s1.setPosition(36);
        b3r11s1.setVarName("b3r11s1");
        add(b3r11s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 754, 45, 24));

        b3r11s2.setErrorlist(errorList);
        b3r11s2.setNextFocusableComponent(b3r12s1);
        b3r11s2.setPanel(this);
        b3r11s2.setPosition(37);
        b3r11s2.setVarName("b3r11s2");
        add(b3r11s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 754, 90, 24));

        b3r12s1.setErrorlist(errorList);
        b3r12s1.setNextFocusableComponent(b3r12s2);
        b3r12s1.setPanel(this);
        b3r12s1.setPosition(38);
        b3r12s1.setVarName("b3r12s1");
        add(b3r12s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 799, 24, 24));

        b3r12s2.setErrorlist(errorList);
        b3r12s2.setNextFocusableComponent(b3r13s1);
        b3r12s2.setPanel(this);
        b3r12s2.setPosition(39);
        b3r12s2.setVarName("b3r12s2");
        add(b3r12s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 862, 290, 80));

        b3r13s1.setErrorlist(errorList);
        b3r13s1.setNextFocusableComponent(b3r13s2);
        b3r13s1.setPanel(this);
        b3r13s1.setPosition(40);
        b3r13s1.setVarName("b3r13s1");
        add(b3r13s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 64, 24, 24));

        b3r13s2.setErrorlist(errorList);
        b3r13s2.setNextFocusableComponent(b3r13s2lainnya);
        b3r13s2.setPanel(this);
        b3r13s2.setPosition(41);
        b3r13s2.setVarName("b3r13s2");
        add(b3r13s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 139, 45, 24));

        b3r13s2lainnya.setErrorlist(errorList);
        b3r13s2lainnya.setNextFocusableComponent(b3r14s1);
        b3r13s2lainnya.setPanel(this);
        b3r13s2lainnya.setPosition(42);
        b3r13s2lainnya.setVarName("b3r13s2lainnya");
        add(b3r13s2lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 175, 172, 15));

        b3r14s1.setErrorlist(errorList);
        b3r14s1.setNextFocusableComponent(b3r14s2);
        b3r14s1.setPanel(this);
        b3r14s1.setPosition(43);
        b3r14s1.setVarName("b3r14s1");
        add(b3r14s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 211, 24, 24));

        b3r14s2.setErrorlist(errorList);
        b3r14s2.setNextFocusableComponent(b3r14s2lainnya);
        b3r14s2.setPanel(this);
        b3r14s2.setPosition(44);
        b3r14s2.setVarName("b3r14s2");
        add(b3r14s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 269, 67, 24));

        b3r14s2lainnya.setErrorlist(errorList);
        b3r14s2lainnya.setNextFocusableComponent(b3r15);
        b3r14s2lainnya.setPanel(this);
        b3r14s2lainnya.setPosition(45);
        b3r14s2lainnya.setVarName("b3r14s2lainnya");
        add(b3r14s2lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 300, 50, 15));

        b3r15.setErrorlist(errorList);
        b3r15.setNextFocusableComponent(b3r16);
        b3r15.setPanel(this);
        b3r15.setPosition(46);
        b3r15.setVarName("b3r15");
        add(b3r15, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 345, 24, 24));

        b3r16.setErrorlist(errorList);
        b3r16.setNextFocusableComponent(b3r17);
        b3r16.setPanel(this);
        b3r16.setPosition(47);
        b3r16.setVarName("b3r16");
        add(b3r16, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 402, 24, 24));

        b3r17.setErrorlist(errorList);
        b3r17.setNextFocusableComponent(b3r18s1t1);
        b3r17.setPanel(this);
        b3r17.setPosition(48);
        b3r17.setVarName("b3r17");
        add(b3r17, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 470, 24, 24));

        b3r18s1t1.setErrorlist(errorList);
        b3r18s1t1.setNextFocusableComponent(b3r18s1t2);
        b3r18s1t1.setPanel(this);
        b3r18s1t1.setPosition(49);
        b3r18s1t1.setVarName("b3r18s1t1");
        add(b3r18s1t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 624, 24, 24));

        b3r18s1t2.setErrorlist(errorList);
        b3r18s1t2.setNextFocusableComponent(b3r18s1t3);
        b3r18s1t2.setPanel(this);
        b3r18s1t2.setPosition(50);
        b3r18s1t2.setVarName("b3r18s1t2");
        add(b3r18s1t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 624, 24, 24));

        b3r18s1t3.setErrorlist(errorList);
        b3r18s1t3.setNextFocusableComponent(b3r18s1t4);
        b3r18s1t3.setPanel(this);
        b3r18s1t3.setPosition(51);
        b3r18s1t3.setVarName("b3r18s1t3");
        add(b3r18s1t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 624, 24, 24));

        b3r18s1t4.setErrorlist(errorList);
        b3r18s1t4.setNextFocusableComponent(b3r18s1t5);
        b3r18s1t4.setPanel(this);
        b3r18s1t4.setPosition(52);
        b3r18s1t4.setVarName("b3r18s1t4");
        add(b3r18s1t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 624, 24, 24));

        b3r18s1t5.setErrorlist(errorList);
        b3r18s1t5.setNextFocusableComponent(b3r18s1t6);
        b3r18s1t5.setPanel(this);
        b3r18s1t5.setPosition(53);
        b3r18s1t5.setVarName("b3r18s1t5");
        add(b3r18s1t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 624, 24, 24));

        b3r18s1t6.setErrorlist(errorList);
        b3r18s1t6.setNextFocusableComponent(b3r18s2t1);
        b3r18s1t6.setPanel(this);
        b3r18s1t6.setPosition(54);
        b3r18s1t6.setVarName("b3r18s1t6");
        add(b3r18s1t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 624, 24, 24));

        b3r18s2t1.setErrorlist(errorList);
        b3r18s2t1.setNextFocusableComponent(b3r18s2t2);
        b3r18s2t1.setPanel(this);
        b3r18s2t1.setPosition(55);
        b3r18s2t1.setVarName("b3r18s2t1");
        add(b3r18s2t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 711, 24, 24));

        b3r18s2t2.setErrorlist(errorList);
        b3r18s2t2.setNextFocusableComponent(b3r18s2t3);
        b3r18s2t2.setPanel(this);
        b3r18s2t2.setPosition(56);
        b3r18s2t2.setVarName("b3r18s2t2");
        add(b3r18s2t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 711, 24, 24));

        b3r18s2t3.setErrorlist(errorList);
        b3r18s2t3.setNextFocusableComponent(b3r18s2t4);
        b3r18s2t3.setPanel(this);
        b3r18s2t3.setPosition(57);
        b3r18s2t3.setVarName("b3r18s2t3");
        add(b3r18s2t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 711, 24, 24));

        b3r18s2t4.setErrorlist(errorList);
        b3r18s2t4.setNextFocusableComponent(b3r18s2t5);
        b3r18s2t4.setPanel(this);
        b3r18s2t4.setPosition(58);
        b3r18s2t4.setVarName("b3r18s2t4");
        add(b3r18s2t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 711, 24, 24));

        b3r18s2t5.setErrorlist(errorList);
        b3r18s2t5.setNextFocusableComponent(b3r18s2t6);
        b3r18s2t5.setPanel(this);
        b3r18s2t5.setPosition(59);
        b3r18s2t5.setVarName("b3r18s2t5");
        add(b3r18s2t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 711, 24, 24));

        b3r18s2t6.setErrorlist(errorList);
        b3r18s2t6.setNextFocusableComponent(b3r19s1t1);
        b3r18s2t6.setPanel(this);
        b3r18s2t6.setPosition(60);
        b3r18s2t6.setVarName("b3r18s2t6");
        add(b3r18s2t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 711, 24, 24));

        b3r19s1t1.setErrorlist(errorList);
        b3r19s1t1.setNextFocusableComponent(b3r19s1t2);
        b3r19s1t1.setPanel(this);
        b3r19s1t1.setPosition(61);
        b3r19s1t1.setVarName("b3r19s1t1");
        add(b3r19s1t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 834, 45, 24));

        b3r19s1t2.setErrorlist(errorList);
        b3r19s1t2.setNextFocusableComponent(b3r19s1t3);
        b3r19s1t2.setPanel(this);
        b3r19s1t2.setPosition(62);
        b3r19s1t2.setVarName("b3r19s1t2");
        add(b3r19s1t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 834, 45, 24));

        b3r19s1t3.setErrorlist(errorList);
        b3r19s1t3.setNextFocusableComponent(b3r19s1t4);
        b3r19s1t3.setPanel(this);
        b3r19s1t3.setPosition(63);
        b3r19s1t3.setVarName("b3r19s1t3");
        add(b3r19s1t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 834, 45, 24));

        b3r19s1t4.setErrorlist(errorList);
        b3r19s1t4.setNextFocusableComponent(b3r19s1t5);
        b3r19s1t4.setPanel(this);
        b3r19s1t4.setPosition(64);
        b3r19s1t4.setVarName("b3r19s1t4");
        add(b3r19s1t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 834, 45, 24));

        b3r19s1t5.setErrorlist(errorList);
        b3r19s1t5.setNextFocusableComponent(b3r19s1t6);
        b3r19s1t5.setPanel(this);
        b3r19s1t5.setPosition(65);
        b3r19s1t5.setVarName("b3r19s1t5");
        add(b3r19s1t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 834, 45, 24));

        b3r19s1t6.setErrorlist(errorList);
        b3r19s1t6.setNextFocusableComponent(b3r19s2t1);
        b3r19s1t6.setPanel(this);
        b3r19s1t6.setPosition(66);
        b3r19s1t6.setVarName("b3r19s1t6");
        add(b3r19s1t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 834, 45, 24));

        b3r19s2t1.setErrorlist(errorList);
        b3r19s2t1.setNextFocusableComponent(b3r19s2t2);
        b3r19s2t1.setPanel(this);
        b3r19s2t1.setPosition(67);
        b3r19s2t1.setVarName("b3r19s2t1");
        add(b3r19s2t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 920, 45, 24));

        b3r19s2t2.setErrorlist(errorList);
        b3r19s2t2.setNextFocusableComponent(b3r19s2t3);
        b3r19s2t2.setPanel(this);
        b3r19s2t2.setPosition(68);
        b3r19s2t2.setVarName("b3r19s2t2");
        add(b3r19s2t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 920, 45, 24));

        b3r19s2t3.setErrorlist(errorList);
        b3r19s2t3.setNextFocusableComponent(b3r19s2t4);
        b3r19s2t3.setPanel(this);
        b3r19s2t3.setPosition(69);
        b3r19s2t3.setVarName("b3r19s2t3");
        add(b3r19s2t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 920, 45, 24));

        b3r19s2t4.setErrorlist(errorList);
        b3r19s2t4.setNextFocusableComponent(b3r19s2t5);
        b3r19s2t4.setPanel(this);
        b3r19s2t4.setPosition(70);
        b3r19s2t4.setVarName("b3r19s2t4");
        add(b3r19s2t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 920, 45, 24));

        b3r19s2t5.setErrorlist(errorList);
        b3r19s2t5.setNextFocusableComponent(b3r19s2t6);
        b3r19s2t5.setPanel(this);
        b3r19s2t5.setPosition(71);
        b3r19s2t5.setVarName("b3r19s2t5");
        add(b3r19s2t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 920, 45, 24));

        b3r19s2t6.setErrorlist(errorList);
        b3r19s2t6.setNextpage(true);
        b3r19s2t6.setPanel(this);
        b3r19s2t6.setPosition(72);
        b3r19s2t6.setVarName("b3r19s2t6");
        add(b3r19s2t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 920, 45, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/U2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.data.view.InputTextField b3r1;
    private pkl55.data.view.InputTextField b3r10;
    private pkl55.data.view.InputTextField b3r10lainnya;
    private pkl55.data.view.InputTextField b3r11s1;
    private pkl55.data.view.InputTextField b3r11s2;
    private pkl55.data.view.InputTextField b3r12s1;
    private pkl55.data.view.InputTextField b3r12s2;
    private pkl55.data.view.InputTextField b3r13s1;
    private pkl55.data.view.InputTextField b3r13s2;
    private pkl55.data.view.InputTextField b3r13s2lainnya;
    private pkl55.data.view.InputTextField b3r14s1;
    private pkl55.data.view.InputTextField b3r14s2;
    private pkl55.data.view.InputTextField b3r14s2lainnya;
    private pkl55.data.view.InputTextField b3r15;
    private pkl55.data.view.InputTextField b3r16;
    private pkl55.data.view.InputTextField b3r17;
    private pkl55.data.view.InputTextField b3r18s1t1;
    private pkl55.data.view.InputTextField b3r18s1t2;
    private pkl55.data.view.InputTextField b3r18s1t3;
    private pkl55.data.view.InputTextField b3r18s1t4;
    private pkl55.data.view.InputTextField b3r18s1t5;
    private pkl55.data.view.InputTextField b3r18s1t6;
    private pkl55.data.view.InputTextField b3r18s2t1;
    private pkl55.data.view.InputTextField b3r18s2t2;
    private pkl55.data.view.InputTextField b3r18s2t3;
    private pkl55.data.view.InputTextField b3r18s2t4;
    private pkl55.data.view.InputTextField b3r18s2t5;
    private pkl55.data.view.InputTextField b3r18s2t6;
    private pkl55.data.view.InputTextField b3r19s1t1;
    private pkl55.data.view.InputTextField b3r19s1t2;
    private pkl55.data.view.InputTextField b3r19s1t3;
    private pkl55.data.view.InputTextField b3r19s1t4;
    private pkl55.data.view.InputTextField b3r19s1t5;
    private pkl55.data.view.InputTextField b3r19s1t6;
    private pkl55.data.view.InputTextField b3r19s2t1;
    private pkl55.data.view.InputTextField b3r19s2t2;
    private pkl55.data.view.InputTextField b3r19s2t3;
    private pkl55.data.view.InputTextField b3r19s2t4;
    private pkl55.data.view.InputTextField b3r19s2t5;
    private pkl55.data.view.InputTextField b3r19s2t6;
    private pkl55.data.view.InputTextField b3r2;
    private pkl55.data.view.InputTextField b3r3;
    private pkl55.data.view.InputTextField b3r4;
    private pkl55.data.view.InputTextField b3r5;
    private pkl55.data.view.InputTextField b3r6;
    private pkl55.data.view.InputTextField b3r7s1;
    private pkl55.data.view.InputTextField b3r7s2;
    private pkl55.data.view.InputTextField b3r8;
    private pkl55.data.view.InputTextField b3r8lainnya;
    private pkl55.data.view.InputTextField b3r9s1;
    private pkl55.data.view.InputTextField b3r9s2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
