/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import java.awt.Component;
import pkl55.data.view.Field;
import pkl55.data.view.Hal;

/**
 *
 * @author ItsFadrur
 */
public class UUHal7 extends Hal {

    /**
     * Creates new form ushal7
     */
    public UUHal7() {
        initComponents();
    }
    @Override
      public void addToView(){
        for (Component comp : getComponents()) {
            if (comp.isVisible()) {
                if (comp instanceof Field) {
                    ((Field) comp).addToView();
                    ((Field) comp).setErrorlist(errorList);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new pkl55.data.view.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(753, 1069));
        setPreferredSize(new java.awt.Dimension(753, 1069));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        textArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        textArea1.setColumns(20);
        textArea1.setRows(5);
        textArea1.setPanel(this);
        textArea1.setVarName("catatan");
        jScrollPane1.setViewportView(textArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 690, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/catatan.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private pkl55.data.view.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
