/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import java.awt.Component;
import pkl55.data.view.Field;
import pkl55.data.view.Hal;

/**
 *
 * @author ItsFadrur
 */
public class UUHal4 extends Hal {

    /**
     * Creates new form ushal4
     */
    public UUHal4() {
        initComponents();
    }
    public void addToView(){
        for (Component comp : getComponents()) {
            if (comp.isVisible()) {
                if (comp instanceof Field) {
                    ((Field) comp).addToView();
                    ((Field) comp).setErrorlist(errorList);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b5r1s1 = new pkl55.data.view.InputTextField();
        b5r1s2 = new pkl55.data.view.InputTextField();
        b5r1s3 = new pkl55.data.view.InputTextField();
        b5r1s4 = new pkl55.data.view.InputTextField();
        b5r1s5 = new pkl55.data.view.InputTextField();
        b5r1s6 = new pkl55.data.view.InputTextField();
        b5r1s7 = new pkl55.data.view.InputTextField();
        b5r2s1 = new pkl55.data.view.InputTextField();
        b5r2s2 = new pkl55.data.view.InputTextField();
        b5r2s3 = new pkl55.data.view.InputTextField();
        b5r3s1t1x1 = new pkl55.data.view.InputTextField();
        b5r3s1t1x2 = new pkl55.data.view.InputTextField();
        b5r3s1t2x1 = new pkl55.data.view.InputTextField();
        b5r3s1t2x2 = new pkl55.data.view.InputTextField();
        b5r3s1t3x1 = new pkl55.data.view.InputTextField();
        b5r3s1t3x2 = new pkl55.data.view.InputTextField();
        b5r3s1t4 = new pkl55.data.view.InputTextField();
        b5r3s2t1x1 = new pkl55.data.view.InputTextField();
        b5r3s2t1x2 = new pkl55.data.view.InputTextField();
        b5r3s2t2x1 = new pkl55.data.view.InputTextField();
        b5r3s2t2x2 = new pkl55.data.view.InputTextField();
        b5r3s2t3x1 = new pkl55.data.view.InputTextField();
        b5r3s2t3x2 = new pkl55.data.view.InputTextField();
        b5r3s2t4 = new pkl55.data.view.InputTextField();
        b5r3s3t1x1 = new pkl55.data.view.InputTextField();
        b5r3s3t1x2 = new pkl55.data.view.InputTextField();
        b5r3s3t2x1 = new pkl55.data.view.InputTextField();
        b5r3s3t2x2 = new pkl55.data.view.InputTextField();
        b5r3s3t3x1 = new pkl55.data.view.InputTextField();
        b5r3s3t3x2 = new pkl55.data.view.InputTextField();
        b5r3s3t4 = new pkl55.data.view.InputTextField();
        b5r3s4t1x1 = new pkl55.data.view.InputTextField();
        b5r3s4t1x2 = new pkl55.data.view.InputTextField();
        b5r3s4t2x1 = new pkl55.data.view.InputTextField();
        b5r3s4t2x2 = new pkl55.data.view.InputTextField();
        b5r3s4t3x1 = new pkl55.data.view.InputTextField();
        b5r3s4t3x2 = new pkl55.data.view.InputTextField();
        b5r3s4t4 = new pkl55.data.view.InputTextField();
        b5r3s5t1x1 = new pkl55.data.view.InputTextField();
        b5r3s5t1x2 = new pkl55.data.view.InputTextField();
        b5r3s5t2x1 = new pkl55.data.view.InputTextField();
        b5r3s5t2x2 = new pkl55.data.view.InputTextField();
        b5r3s5t3x1 = new pkl55.data.view.InputTextField();
        b5r3s5t3x2 = new pkl55.data.view.InputTextField();
        b5r3s5t4 = new pkl55.data.view.InputTextField();
        b5r3s6t1x1 = new pkl55.data.view.InputTextField();
        b5r3s6t1x2 = new pkl55.data.view.InputTextField();
        b5r3s6t2x1 = new pkl55.data.view.InputTextField();
        b5r3s6t2x2 = new pkl55.data.view.InputTextField();
        b5r3s6t3x1 = new pkl55.data.view.InputTextField();
        b5r3s6t3x2 = new pkl55.data.view.InputTextField();
        b5r3s6t4 = new pkl55.data.view.InputTextField();
        b5r3s7t1x1 = new pkl55.data.view.InputTextField();
        b5r3s7t1x2 = new pkl55.data.view.InputTextField();
        b5r3s7t2x1 = new pkl55.data.view.InputTextField();
        b5r3s7t2x2 = new pkl55.data.view.InputTextField();
        b5r3s7t3x1 = new pkl55.data.view.InputTextField();
        b5r3s7t3x2 = new pkl55.data.view.InputTextField();
        b5r3s7t4 = new pkl55.data.view.InputTextField();
        b5r3s8t1x1 = new pkl55.data.view.InputTextField();
        b5r3s8t1x2 = new pkl55.data.view.InputTextField();
        b5r3s8t2x1 = new pkl55.data.view.InputTextField();
        b5r3s8t2x2 = new pkl55.data.view.InputTextField();
        b5r3s8t3x1 = new pkl55.data.view.InputTextField();
        b5r3s8t3x2 = new pkl55.data.view.InputTextField();
        b5r3s8t4 = new pkl55.data.view.InputTextField();
        b5r3s9t1x1 = new pkl55.data.view.InputTextField();
        b5r3s9t1x2 = new pkl55.data.view.InputTextField();
        b5r3s9t2x1 = new pkl55.data.view.InputTextField();
        b5r3s9t2x2 = new pkl55.data.view.InputTextField();
        b5r3s9t3x1 = new pkl55.data.view.InputTextField();
        b5r3s9t3x2 = new pkl55.data.view.InputTextField();
        b5r3s9t4 = new pkl55.data.view.InputTextField();
        b5r3s10t1x1 = new pkl55.data.view.InputTextField();
        b5r3s10t1x2 = new pkl55.data.view.InputTextField();
        b5r3s10t2x1 = new pkl55.data.view.InputTextField();
        b5r3s10t2x2 = new pkl55.data.view.InputTextField();
        b5r3s10t3x1 = new pkl55.data.view.InputTextField();
        b5r3s10t3x2 = new pkl55.data.view.InputTextField();
        b5r3s10t4 = new pkl55.data.view.InputTextField();
        b5r3s11t1x1 = new pkl55.data.view.InputTextField();
        b5r3s11t1x2 = new pkl55.data.view.InputTextField();
        b5r3s11t2x1 = new pkl55.data.view.InputTextField();
        b5r3s11t2x2 = new pkl55.data.view.InputTextField();
        b5r3s11t3x1 = new pkl55.data.view.InputTextField();
        b5r3s11t3x2 = new pkl55.data.view.InputTextField();
        b5r3s11t4 = new pkl55.data.view.InputTextField();
        b5r4s1 = new pkl55.data.view.InputTextField();
        b5r4s2 = new pkl55.data.view.InputTextField();
        b5r5s1 = new pkl55.data.view.InputTextField();
        b5r5s2 = new pkl55.data.view.InputTextField();
        b5r6 = new pkl55.data.view.InputTextField();
        b5r7 = new pkl55.data.view.InputTextField();
        Halaman4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(753, 1069));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b5r1s1.setErrorlist(errorList);
        b5r1s1.setNextFocusableComponent(b5r1s2);
        b5r1s1.setPanel(this);
        b5r1s1.setPosition(104);
        b5r1s1.setVarName("b5r1s1");
        add(b5r1s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 99, 44, 23));

        b5r1s2.setErrorlist(errorList);
        b5r1s2.setNextFocusableComponent(b5r1s3);
        b5r1s2.setPanel(this);
        b5r1s2.setPosition(105);
        b5r1s2.setVarName("b5r1s2");
        add(b5r1s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 99, 44, 23));

        b5r1s3.setErrorlist(errorList);
        b5r1s3.setNextFocusableComponent(b5r1s4);
        b5r1s3.setPanel(this);
        b5r1s3.setPosition(106);
        b5r1s3.setVarName("b5r1s3");
        add(b5r1s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 99, 44, 23));

        b5r1s4.setErrorlist(errorList);
        b5r1s4.setNextFocusableComponent(b5r1s5);
        b5r1s4.setPanel(this);
        b5r1s4.setPosition(107);
        b5r1s4.setVarName("b5r1s4");
        b5r1s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r1s4ActionPerformed(evt);
            }
        });
        add(b5r1s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 99, 44, 23));

        b5r1s5.setErrorlist(errorList);
        b5r1s5.setNextFocusableComponent(b5r1s6);
        b5r1s5.setPanel(this);
        b5r1s5.setPosition(108);
        b5r1s5.setVarName("b5r1s5");
        b5r1s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r1s5ActionPerformed(evt);
            }
        });
        add(b5r1s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 99, 44, 23));

        b5r1s6.setErrorlist(errorList);
        b5r1s6.setNextFocusableComponent(b5r1s7);
        b5r1s6.setPanel(this);
        b5r1s6.setPosition(109);
        b5r1s6.setVarName("b5r1s6");
        b5r1s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r1s6ActionPerformed(evt);
            }
        });
        add(b5r1s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 99, 44, 23));

        b5r1s7.setErrorlist(errorList);
        b5r1s7.setNextFocusableComponent(b5r2s1);
        b5r1s7.setPanel(this);
        b5r1s7.setPosition(110);
        b5r1s7.setVarName("b5r1s7");
        b5r1s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r1s7ActionPerformed(evt);
            }
        });
        add(b5r1s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 99, 44, 23));

        b5r2s1.setErrorlist(errorList);
        b5r2s1.setNextFocusableComponent(b5r2s2);
        b5r2s1.setPanel(this);
        b5r2s1.setPosition(111);
        b5r2s1.setVarName("b5r2s1");
        b5r2s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r2s1ActionPerformed(evt);
            }
        });
        add(b5r2s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 191, 65, 23));

        b5r2s2.setErrorlist(errorList);
        b5r2s2.setNextFocusableComponent(b5r2s3);
        b5r2s2.setPanel(this);
        b5r2s2.setPosition(112);
        b5r2s2.setVarName("b5r2s2");
        b5r2s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r2s2ActionPerformed(evt);
            }
        });
        add(b5r2s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 220, 65, 23));

        b5r2s3.setErrorlist(errorList);
        b5r2s3.setNextFocusableComponent(b5r3s1t1x1);
        b5r2s3.setPanel(this);
        b5r2s3.setPosition(113);
        b5r2s3.setVarName("b5r2s3");
        b5r2s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r2s3ActionPerformed(evt);
            }
        });
        add(b5r2s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 248, 65, 23));

        b5r3s1t1x1.setErrorlist(errorList);
        b5r3s1t1x1.setNextFocusableComponent(b5r3s2t1x1);
        b5r3s1t1x1.setPanel(this);
        b5r3s1t1x1.setPosition(114);
        b5r3s1t1x1.setVarName("b5r3s1t1x1");
        b5r3s1t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s1t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 376, 66, 23));

        b5r3s1t1x2.setErrorlist(errorList);
        b5r3s1t1x2.setNextFocusableComponent(b5r3s2t1x2);
        b5r3s1t1x2.setPanel(this);
        b5r3s1t1x2.setPosition(125);
        b5r3s1t1x2.setVarName("b5r3s1t1x2");
        b5r3s1t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s1t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 376, 66, 23));

        b5r3s1t2x1.setErrorlist(errorList);
        b5r3s1t2x1.setNextFocusableComponent(b5r3s2t2x1);
        b5r3s1t2x1.setPanel(this);
        b5r3s1t2x1.setPosition(136);
        b5r3s1t2x1.setVarName("b5r3s1t2x1");
        b5r3s1t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s1t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 376, 66, 23));

        b5r3s1t2x2.setErrorlist(errorList);
        b5r3s1t2x2.setNextFocusableComponent(b5r3s2t2x2);
        b5r3s1t2x2.setPanel(this);
        b5r3s1t2x2.setPosition(147);
        b5r3s1t2x2.setVarName("b5r3s1t2x2");
        b5r3s1t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s1t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 376, 66, 23));

        b5r3s1t3x1.setErrorlist(errorList);
        b5r3s1t3x1.setNextFocusableComponent(b5r3s2t3x1);
        b5r3s1t3x1.setPanel(this);
        b5r3s1t3x1.setPosition(158);
        b5r3s1t3x1.setVarName("b5r3s1t3x1");
        b5r3s1t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s1t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 376, 66, 23));

        b5r3s1t3x2.setErrorlist(errorList);
        b5r3s1t3x2.setNextFocusableComponent(b5r3s2t3x2);
        b5r3s1t3x2.setPanel(this);
        b5r3s1t3x2.setPosition(169);
        b5r3s1t3x2.setVarName("b5r3s1t3x2");
        b5r3s1t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s1t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 376, 66, 23));

        b5r3s1t4.setErrorlist(errorList);
        b5r3s1t4.setNextFocusableComponent(b5r3s2t4);
        b5r3s1t4.setPanel(this);
        b5r3s1t4.setPosition(180);
        b5r3s1t4.setVarName("b5r3s1t4");
        b5r3s1t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s1t4ActionPerformed(evt);
            }
        });
        add(b5r3s1t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 376, 66, 23));

        b5r3s2t1x1.setErrorlist(errorList);
        b5r3s2t1x1.setNextFocusableComponent(b5r3s3t1x1);
        b5r3s2t1x1.setPanel(this);
        b5r3s2t1x1.setVarName("b5r3s2t1x1");
        b5r3s2t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s2t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 405, 66, 23));

        b5r3s2t1x2.setErrorlist(errorList);
        b5r3s2t1x2.setNextFocusableComponent(b5r3s3t1x2);
        b5r3s2t1x2.setPanel(this);
        b5r3s2t1x2.setPosition(126);
        b5r3s2t1x2.setVarName("b5r3s2t1x2");
        b5r3s2t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s2t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 405, 66, 23));

        b5r3s2t2x1.setErrorlist(errorList);
        b5r3s2t2x1.setNextFocusableComponent(b5r3s3t2x1);
        b5r3s2t2x1.setPanel(this);
        b5r3s2t2x1.setPosition(137);
        b5r3s2t2x1.setVarName("b5r3s2t2x1");
        b5r3s2t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s2t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 405, 66, 23));

        b5r3s2t2x2.setErrorlist(errorList);
        b5r3s2t2x2.setNextFocusableComponent(b5r3s3t2x2);
        b5r3s2t2x2.setPanel(this);
        b5r3s2t2x2.setPosition(148);
        b5r3s2t2x2.setVarName("b5r3s2t2x2");
        b5r3s2t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s2t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 405, 66, 23));

        b5r3s2t3x1.setErrorlist(errorList);
        b5r3s2t3x1.setNextFocusableComponent(b5r3s3t3x1);
        b5r3s2t3x1.setPanel(this);
        b5r3s2t3x1.setPosition(159);
        b5r3s2t3x1.setVarName("b5r3s2t3x1");
        b5r3s2t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s2t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 405, 66, 23));

        b5r3s2t3x2.setErrorlist(errorList);
        b5r3s2t3x2.setNextFocusableComponent(b5r3s3t3x2);
        b5r3s2t3x2.setPanel(this);
        b5r3s2t3x2.setPosition(170);
        b5r3s2t3x2.setVarName("b5r3s2t3x2");
        b5r3s2t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s2t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 405, 66, 23));

        b5r3s2t4.setErrorlist(errorList);
        b5r3s2t4.setNextFocusableComponent(b5r3s3t4);
        b5r3s2t4.setPanel(this);
        b5r3s2t4.setPosition(181);
        b5r3s2t4.setVarName("b5r3s2t4");
        b5r3s2t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s2t4ActionPerformed(evt);
            }
        });
        add(b5r3s2t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 405, 66, 23));

        b5r3s3t1x1.setErrorlist(errorList);
        b5r3s3t1x1.setNextFocusableComponent(b5r3s4t1x1);
        b5r3s3t1x1.setPanel(this);
        b5r3s3t1x1.setPosition(116);
        b5r3s3t1x1.setVarName("b5r3s3t1x1");
        b5r3s3t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s3t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 430, 66, 23));

        b5r3s3t1x2.setErrorlist(errorList);
        b5r3s3t1x2.setNextFocusableComponent(b5r3s4t1x2);
        b5r3s3t1x2.setPanel(this);
        b5r3s3t1x2.setPosition(127);
        b5r3s3t1x2.setVarName("b5r3s3t1x2");
        b5r3s3t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s3t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 430, 66, 23));

        b5r3s3t2x1.setErrorlist(errorList);
        b5r3s3t2x1.setNextFocusableComponent(b5r3s4t2x1);
        b5r3s3t2x1.setPanel(this);
        b5r3s3t2x1.setPosition(138);
        b5r3s3t2x1.setVarName("b5r3s3t2x1");
        b5r3s3t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s3t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 66, 23));

        b5r3s3t2x2.setErrorlist(errorList);
        b5r3s3t2x2.setNextFocusableComponent(b5r3s4t2x2);
        b5r3s3t2x2.setPanel(this);
        b5r3s3t2x2.setPosition(149);
        b5r3s3t2x2.setVarName("b5r3s3t2x2");
        b5r3s3t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s3t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 430, 66, 23));

        b5r3s3t3x1.setErrorlist(errorList);
        b5r3s3t3x1.setNextFocusableComponent(b5r3s4t3x1);
        b5r3s3t3x1.setPanel(this);
        b5r3s3t3x1.setPosition(160);
        b5r3s3t3x1.setVarName("b5r3s3t3x1");
        b5r3s3t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s3t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 430, 66, 23));

        b5r3s3t3x2.setErrorlist(errorList);
        b5r3s3t3x2.setNextFocusableComponent(b5r3s4t3x2);
        b5r3s3t3x2.setPanel(this);
        b5r3s3t3x2.setPosition(171);
        b5r3s3t3x2.setVarName("b5r3s3t3x2");
        b5r3s3t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s3t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 430, 66, 23));

        b5r3s3t4.setErrorlist(errorList);
        b5r3s3t4.setNextFocusableComponent(b5r3s4t4);
        b5r3s3t4.setPanel(this);
        b5r3s3t4.setPosition(182);
        b5r3s3t4.setVarName("b5r3s3t4");
        b5r3s3t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s3t4ActionPerformed(evt);
            }
        });
        add(b5r3s3t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 430, 66, 23));

        b5r3s4t1x1.setErrorlist(errorList);
        b5r3s4t1x1.setNextFocusableComponent(b5r3s5t1x1);
        b5r3s4t1x1.setPanel(this);
        b5r3s4t1x1.setPosition(117);
        b5r3s4t1x1.setVarName("b5r3s4t1x1");
        b5r3s4t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s4t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 458, 66, 23));

        b5r3s4t1x2.setErrorlist(errorList);
        b5r3s4t1x2.setNextFocusableComponent(b5r3s5t1x2);
        b5r3s4t1x2.setPanel(this);
        b5r3s4t1x2.setPosition(128);
        b5r3s4t1x2.setVarName("b5r3s4t1x2");
        b5r3s4t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s4t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 458, 66, 23));

        b5r3s4t2x1.setErrorlist(errorList);
        b5r3s4t2x1.setNextFocusableComponent(b5r3s5t2x1);
        b5r3s4t2x1.setPanel(this);
        b5r3s4t2x1.setPosition(139);
        b5r3s4t2x1.setVarName("b5r3s4t2x1");
        b5r3s4t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s4t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 458, 66, 23));

        b5r3s4t2x2.setErrorlist(errorList);
        b5r3s4t2x2.setNextFocusableComponent(b5r3s5t2x2);
        b5r3s4t2x2.setPanel(this);
        b5r3s4t2x2.setPosition(150);
        b5r3s4t2x2.setVarName("b5r3s4t2x2");
        b5r3s4t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s4t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 458, 66, 23));

        b5r3s4t3x1.setErrorlist(errorList);
        b5r3s4t3x1.setNextFocusableComponent(b5r3s5t3x1);
        b5r3s4t3x1.setPanel(this);
        b5r3s4t3x1.setPosition(161);
        b5r3s4t3x1.setVarName("b5r3s4t3x1");
        b5r3s4t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s4t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 458, 66, 23));

        b5r3s4t3x2.setErrorlist(errorList);
        b5r3s4t3x2.setNextFocusableComponent(b5r3s5t3x2);
        b5r3s4t3x2.setPanel(this);
        b5r3s4t3x2.setPosition(172);
        b5r3s4t3x2.setVarName("b5r3s4t3x2");
        b5r3s4t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s4t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 458, 66, 23));

        b5r3s4t4.setErrorlist(errorList);
        b5r3s4t4.setNextFocusableComponent(b5r3s5t4);
        b5r3s4t4.setPanel(this);
        b5r3s4t4.setPosition(183);
        b5r3s4t4.setVarName("b5r3s4t4");
        b5r3s4t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s4t4ActionPerformed(evt);
            }
        });
        add(b5r3s4t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 458, 66, 23));

        b5r3s5t1x1.setErrorlist(errorList);
        b5r3s5t1x1.setNextFocusableComponent(b5r3s6t1x1);
        b5r3s5t1x1.setPanel(this);
        b5r3s5t1x1.setPosition(118);
        b5r3s5t1x1.setVarName("b5r3s5t1x1");
        b5r3s5t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s5t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 486, 66, 23));

        b5r3s5t1x2.setErrorlist(errorList);
        b5r3s5t1x2.setNextFocusableComponent(b5r3s6t1x2);
        b5r3s5t1x2.setPanel(this);
        b5r3s5t1x2.setPosition(129);
        b5r3s5t1x2.setVarName("b5r3s5t1x2");
        b5r3s5t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s5t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 486, 66, 23));

        b5r3s5t2x1.setErrorlist(errorList);
        b5r3s5t2x1.setNextFocusableComponent(b5r3s6t2x1);
        b5r3s5t2x1.setPanel(this);
        b5r3s5t2x1.setPosition(140);
        b5r3s5t2x1.setVarName("b5r3s5t2x1");
        b5r3s5t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s5t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 486, 66, 23));

        b5r3s5t2x2.setErrorlist(errorList);
        b5r3s5t2x2.setNextFocusableComponent(b5r3s6t2x2);
        b5r3s5t2x2.setPanel(this);
        b5r3s5t2x2.setPosition(151);
        b5r3s5t2x2.setVarName("b5r3s5t2x2");
        b5r3s5t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s5t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 486, 66, 23));

        b5r3s5t3x1.setErrorlist(errorList);
        b5r3s5t3x1.setNextFocusableComponent(b5r3s6t3x1);
        b5r3s5t3x1.setPanel(this);
        b5r3s5t3x1.setPosition(162);
        b5r3s5t3x1.setVarName("b5r3s5t3x1");
        b5r3s5t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s5t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 486, 66, 23));

        b5r3s5t3x2.setErrorlist(errorList);
        b5r3s5t3x2.setNextFocusableComponent(b5r3s6t3x2);
        b5r3s5t3x2.setPanel(this);
        b5r3s5t3x2.setPosition(173);
        b5r3s5t3x2.setVarName("b5r3s5t3x2");
        b5r3s5t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s5t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 486, 66, 23));

        b5r3s5t4.setErrorlist(errorList);
        b5r3s5t4.setNextFocusableComponent(b5r3s6t4);
        b5r3s5t4.setPanel(this);
        b5r3s5t4.setPosition(184);
        b5r3s5t4.setVarName("b5r3s5t4");
        b5r3s5t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s5t4ActionPerformed(evt);
            }
        });
        add(b5r3s5t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 486, 66, 23));

        b5r3s6t1x1.setErrorlist(errorList);
        b5r3s6t1x1.setNextFocusableComponent(b5r3s7t1x1);
        b5r3s6t1x1.setPanel(this);
        b5r3s6t1x1.setPosition(119);
        b5r3s6t1x1.setVarName("b5r3s6t1x1");
        b5r3s6t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s6t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 515, 66, 23));

        b5r3s6t1x2.setErrorlist(errorList);
        b5r3s6t1x2.setNextFocusableComponent(b5r3s7t1x2);
        b5r3s6t1x2.setPanel(this);
        b5r3s6t1x2.setPosition(130);
        b5r3s6t1x2.setVarName("b5r3s6t1x2");
        b5r3s6t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s6t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 515, 66, 23));

        b5r3s6t2x1.setErrorlist(errorList);
        b5r3s6t2x1.setNextFocusableComponent(b5r3s7t2x1);
        b5r3s6t2x1.setPanel(this);
        b5r3s6t2x1.setPosition(141);
        b5r3s6t2x1.setVarName("b5r3s6t2x1");
        b5r3s6t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s6t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 515, 66, 23));

        b5r3s6t2x2.setErrorlist(errorList);
        b5r3s6t2x2.setNextFocusableComponent(b5r3s7t2x2);
        b5r3s6t2x2.setPanel(this);
        b5r3s6t2x2.setPosition(152);
        b5r3s6t2x2.setVarName("b5r3s6t2x2");
        b5r3s6t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s6t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 515, 66, 23));

        b5r3s6t3x1.setErrorlist(errorList);
        b5r3s6t3x1.setNextFocusableComponent(b5r3s7t3x1);
        b5r3s6t3x1.setPanel(this);
        b5r3s6t3x1.setPosition(163);
        b5r3s6t3x1.setVarName("b5r3s6t3x1");
        b5r3s6t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s6t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 515, 66, 23));

        b5r3s6t3x2.setErrorlist(errorList);
        b5r3s6t3x2.setNextFocusableComponent(b5r3s7t3x2);
        b5r3s6t3x2.setPanel(this);
        b5r3s6t3x2.setPosition(174);
        b5r3s6t3x2.setVarName("b5r3s6t3x2");
        b5r3s6t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s6t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 515, 66, 23));

        b5r3s6t4.setErrorlist(errorList);
        b5r3s6t4.setNextFocusableComponent(b5r3s7t4);
        b5r3s6t4.setPanel(this);
        b5r3s6t4.setPosition(185);
        b5r3s6t4.setVarName("b5r3s6t4");
        b5r3s6t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s6t4ActionPerformed(evt);
            }
        });
        add(b5r3s6t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 515, 66, 23));

        b5r3s7t1x1.setErrorlist(errorList);
        b5r3s7t1x1.setNextFocusableComponent(b5r3s8t1x1);
        b5r3s7t1x1.setPanel(this);
        b5r3s7t1x1.setPosition(120);
        b5r3s7t1x1.setVarName("b5r3s7t1x1");
        b5r3s7t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s7t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 543, 66, 23));

        b5r3s7t1x2.setErrorlist(errorList);
        b5r3s7t1x2.setNextFocusableComponent(b5r3s8t1x2);
        b5r3s7t1x2.setPanel(this);
        b5r3s7t1x2.setPosition(131);
        b5r3s7t1x2.setVarName("b5r3s7t1x2");
        b5r3s7t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s7t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 543, 66, 23));

        b5r3s7t2x1.setErrorlist(errorList);
        b5r3s7t2x1.setNextFocusableComponent(b5r3s8t2x1);
        b5r3s7t2x1.setPanel(this);
        b5r3s7t2x1.setPosition(142);
        b5r3s7t2x1.setVarName("b5r3s7t2x1");
        b5r3s7t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s7t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 543, 66, 23));

        b5r3s7t2x2.setErrorlist(errorList);
        b5r3s7t2x2.setNextFocusableComponent(b5r3s8t2x2);
        b5r3s7t2x2.setPanel(this);
        b5r3s7t2x2.setPosition(153);
        b5r3s7t2x2.setVarName("b5r3s7t2x2");
        b5r3s7t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s7t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 543, 66, 23));

        b5r3s7t3x1.setErrorlist(errorList);
        b5r3s7t3x1.setNextFocusableComponent(b5r3s8t3x1);
        b5r3s7t3x1.setPanel(this);
        b5r3s7t3x1.setPosition(164);
        b5r3s7t3x1.setVarName("b5r3s7t3x1");
        b5r3s7t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s7t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 543, 66, 23));

        b5r3s7t3x2.setErrorlist(errorList);
        b5r3s7t3x2.setNextFocusableComponent(b5r3s8t3x2);
        b5r3s7t3x2.setPanel(this);
        b5r3s7t3x2.setPosition(175);
        b5r3s7t3x2.setVarName("b5r3s7t3x2");
        b5r3s7t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s7t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 543, 66, 23));

        b5r3s7t4.setErrorlist(errorList);
        b5r3s7t4.setNextFocusableComponent(b5r3s8t4);
        b5r3s7t4.setPanel(this);
        b5r3s7t4.setPosition(186);
        b5r3s7t4.setVarName("b5r3s7t4");
        b5r3s7t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s7t4ActionPerformed(evt);
            }
        });
        add(b5r3s7t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 543, 66, 23));

        b5r3s8t1x1.setErrorlist(errorList);
        b5r3s8t1x1.setNextFocusableComponent(b5r3s9t1x1);
        b5r3s8t1x1.setPanel(this);
        b5r3s8t1x1.setPosition(121);
        b5r3s8t1x1.setVarName("b5r3s8t1x1");
        b5r3s8t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s8t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 572, 66, 23));

        b5r3s8t1x2.setErrorlist(errorList);
        b5r3s8t1x2.setNextFocusableComponent(b5r3s9t1x2);
        b5r3s8t1x2.setPanel(this);
        b5r3s8t1x2.setPosition(132);
        b5r3s8t1x2.setVarName("b5r3s8t1x2");
        b5r3s8t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s8t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 572, 66, 23));

        b5r3s8t2x1.setErrorlist(errorList);
        b5r3s8t2x1.setNextFocusableComponent(b5r3s9t2x1);
        b5r3s8t2x1.setPanel(this);
        b5r3s8t2x1.setPosition(143);
        b5r3s8t2x1.setVarName("b5r3s8t2x1");
        b5r3s8t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s8t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 572, 66, 23));

        b5r3s8t2x2.setErrorlist(errorList);
        b5r3s8t2x2.setNextFocusableComponent(b5r3s9t2x2);
        b5r3s8t2x2.setPanel(this);
        b5r3s8t2x2.setPosition(154);
        b5r3s8t2x2.setVarName("b5r3s8t2x2");
        b5r3s8t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s8t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 572, 66, 23));

        b5r3s8t3x1.setErrorlist(errorList);
        b5r3s8t3x1.setNextFocusableComponent(b5r3s9t3x1);
        b5r3s8t3x1.setPanel(this);
        b5r3s8t3x1.setPosition(165);
        b5r3s8t3x1.setVarName("b5r3s8t3x1");
        b5r3s8t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s8t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 572, 66, 23));

        b5r3s8t3x2.setErrorlist(errorList);
        b5r3s8t3x2.setNextFocusableComponent(b5r3s9t3x2);
        b5r3s8t3x2.setPanel(this);
        b5r3s8t3x2.setPosition(176);
        b5r3s8t3x2.setVarName("b5r3s8t3x2");
        b5r3s8t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s8t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 572, 66, 23));

        b5r3s8t4.setErrorlist(errorList);
        b5r3s8t4.setNextFocusableComponent(b5r3s9t4);
        b5r3s8t4.setPanel(this);
        b5r3s8t4.setPosition(187);
        b5r3s8t4.setVarName("b5r3s8t4");
        b5r3s8t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s8t4ActionPerformed(evt);
            }
        });
        add(b5r3s8t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 572, 66, 23));

        b5r3s9t1x1.setErrorlist(errorList);
        b5r3s9t1x1.setNextFocusableComponent(b5r3s10t1x1);
        b5r3s9t1x1.setPanel(this);
        b5r3s9t1x1.setPosition(122);
        b5r3s9t1x1.setVarName("b5r3s9t1x1");
        b5r3s9t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s9t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 600, 66, 23));

        b5r3s9t1x2.setErrorlist(errorList);
        b5r3s9t1x2.setNextFocusableComponent(b5r3s10t1x2);
        b5r3s9t1x2.setPanel(this);
        b5r3s9t1x2.setPosition(133);
        b5r3s9t1x2.setVarName("b5r3s9t1x2");
        b5r3s9t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s9t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 600, 66, 23));

        b5r3s9t2x1.setErrorlist(errorList);
        b5r3s9t2x1.setNextFocusableComponent(b5r3s10t2x1);
        b5r3s9t2x1.setPanel(this);
        b5r3s9t2x1.setPosition(144);
        b5r3s9t2x1.setVarName("b5r3s9t2x1");
        b5r3s9t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s9t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 66, 23));

        b5r3s9t2x2.setErrorlist(errorList);
        b5r3s9t2x2.setNextFocusableComponent(b5r3s10t2x2);
        b5r3s9t2x2.setPanel(this);
        b5r3s9t2x2.setPosition(155);
        b5r3s9t2x2.setVarName("b5r3s9t2x2");
        b5r3s9t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s9t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 600, 66, 23));

        b5r3s9t3x1.setErrorlist(errorList);
        b5r3s9t3x1.setNextFocusableComponent(b5r3s10t3x1);
        b5r3s9t3x1.setPanel(this);
        b5r3s9t3x1.setPosition(166);
        b5r3s9t3x1.setVarName("b5r3s9t3x1");
        b5r3s9t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s9t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 600, 66, 23));

        b5r3s9t3x2.setErrorlist(errorList);
        b5r3s9t3x2.setNextFocusableComponent(b5r3s10t3x2);
        b5r3s9t3x2.setPanel(this);
        b5r3s9t3x2.setPosition(177);
        b5r3s9t3x2.setVarName("b5r3s9t3x2");
        b5r3s9t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s9t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 600, 66, 23));

        b5r3s9t4.setErrorlist(errorList);
        b5r3s9t4.setNextFocusableComponent(b5r3s10t4);
        b5r3s9t4.setPanel(this);
        b5r3s9t4.setPosition(188);
        b5r3s9t4.setVarName("b5r3s9t4");
        b5r3s9t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s9t4ActionPerformed(evt);
            }
        });
        add(b5r3s9t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 600, 66, 23));

        b5r3s10t1x1.setErrorlist(errorList);
        b5r3s10t1x1.setNextFocusableComponent(b5r3s11t1x1);
        b5r3s10t1x1.setPanel(this);
        b5r3s10t1x1.setPosition(123);
        b5r3s10t1x1.setVarName("b5r3s10t1x1");
        b5r3s10t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s10t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 629, 66, 23));

        b5r3s10t1x2.setErrorlist(errorList);
        b5r3s10t1x2.setNextFocusableComponent(b5r3s11t1x2);
        b5r3s10t1x2.setPanel(this);
        b5r3s10t1x2.setPosition(134);
        b5r3s10t1x2.setVarName("b5r3s10t1x2");
        b5r3s10t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s10t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 629, 66, 23));

        b5r3s10t2x1.setErrorlist(errorList);
        b5r3s10t2x1.setNextFocusableComponent(b5r3s11t2x1);
        b5r3s10t2x1.setPanel(this);
        b5r3s10t2x1.setPosition(145);
        b5r3s10t2x1.setVarName("b5r3s10t2x1");
        b5r3s10t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s10t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 629, 66, 23));

        b5r3s10t2x2.setErrorlist(errorList);
        b5r3s10t2x2.setNextFocusableComponent(b5r3s11t2x2);
        b5r3s10t2x2.setPanel(this);
        b5r3s10t2x2.setPosition(156);
        b5r3s10t2x2.setVarName("b5r3s10t2x2");
        b5r3s10t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s10t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 629, 66, 23));

        b5r3s10t3x1.setErrorlist(errorList);
        b5r3s10t3x1.setNextFocusableComponent(b5r3s11t3x1);
        b5r3s10t3x1.setPanel(this);
        b5r3s10t3x1.setPosition(167);
        b5r3s10t3x1.setVarName("b5r3s10t3x1");
        b5r3s10t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s10t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 629, 66, 23));

        b5r3s10t3x2.setErrorlist(errorList);
        b5r3s10t3x2.setNextFocusableComponent(b5r3s11t3x2);
        b5r3s10t3x2.setPanel(this);
        b5r3s10t3x2.setPosition(178);
        b5r3s10t3x2.setVarName("b5r3s10t3x2");
        b5r3s10t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s10t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 629, 66, 23));

        b5r3s10t4.setErrorlist(errorList);
        b5r3s10t4.setNextFocusableComponent(b5r3s11t4);
        b5r3s10t4.setPanel(this);
        b5r3s10t4.setPosition(189);
        b5r3s10t4.setVarName("b5r3s10t4");
        b5r3s10t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s10t4ActionPerformed(evt);
            }
        });
        add(b5r3s10t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 629, 66, 23));

        b5r3s11t1x1.setErrorlist(errorList);
        b5r3s11t1x1.setNextFocusableComponent(b5r3s1t1x2);
        b5r3s11t1x1.setPanel(this);
        b5r3s11t1x1.setPosition(124);
        b5r3s11t1x1.setVarName("b5r3s11t1x1");
        b5r3s11t1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t1x1ActionPerformed(evt);
            }
        });
        add(b5r3s11t1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 657, 66, 23));

        b5r3s11t1x2.setErrorlist(errorList);
        b5r3s11t1x2.setNextFocusableComponent(b5r3s1t2x1);
        b5r3s11t1x2.setPanel(this);
        b5r3s11t1x2.setPosition(135);
        b5r3s11t1x2.setVarName("b5r3s11t1x2");
        b5r3s11t1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t1x2ActionPerformed(evt);
            }
        });
        add(b5r3s11t1x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 657, 66, 23));

        b5r3s11t2x1.setErrorlist(errorList);
        b5r3s11t2x1.setNextFocusableComponent(b5r3s1t2x2);
        b5r3s11t2x1.setPanel(this);
        b5r3s11t2x1.setPosition(146);
        b5r3s11t2x1.setVarName("b5r3s11t2x1");
        b5r3s11t2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t2x1ActionPerformed(evt);
            }
        });
        add(b5r3s11t2x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 657, 66, 23));

        b5r3s11t2x2.setErrorlist(errorList);
        b5r3s11t2x2.setNextFocusableComponent(b5r3s1t3x1);
        b5r3s11t2x2.setPanel(this);
        b5r3s11t2x2.setPosition(157);
        b5r3s11t2x2.setVarName("b5r3s11t2x2");
        b5r3s11t2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t2x2ActionPerformed(evt);
            }
        });
        add(b5r3s11t2x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 657, 66, 23));

        b5r3s11t3x1.setErrorlist(errorList);
        b5r3s11t3x1.setNextFocusableComponent(b5r3s1t3x2);
        b5r3s11t3x1.setPanel(this);
        b5r3s11t3x1.setPosition(168);
        b5r3s11t3x1.setVarName("b5r3s11t3x1");
        b5r3s11t3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t3x1ActionPerformed(evt);
            }
        });
        add(b5r3s11t3x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 657, 66, 23));

        b5r3s11t3x2.setErrorlist(errorList);
        b5r3s11t3x2.setNextFocusableComponent(b5r3s1t4);
        b5r3s11t3x2.setPanel(this);
        b5r3s11t3x2.setPosition(179);
        b5r3s11t3x2.setVarName("b5r3s11t3x2");
        b5r3s11t3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t3x2ActionPerformed(evt);
            }
        });
        add(b5r3s11t3x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 657, 66, 23));

        b5r3s11t4.setErrorlist(errorList);
        b5r3s11t4.setNextFocusableComponent(b5r4s1);
        b5r3s11t4.setPanel(this);
        b5r3s11t4.setPosition(190);
        b5r3s11t4.setVarName("b5r3s11t4");
        b5r3s11t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r3s11t4ActionPerformed(evt);
            }
        });
        add(b5r3s11t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 657, 66, 23));

        b5r4s1.setErrorlist(errorList);
        b5r4s1.setNextFocusableComponent(b5r4s2);
        b5r4s1.setPanel(this);
        b5r4s1.setPosition(191);
        b5r4s1.setVarName("b5r4s1");
        b5r4s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r4s1ActionPerformed(evt);
            }
        });
        add(b5r4s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 760, 65, 23));

        b5r4s2.setErrorlist(errorList);
        b5r4s2.setNextFocusableComponent(b5r5s1);
        b5r4s2.setPanel(this);
        b5r4s2.setPosition(192);
        b5r4s2.setVarName("b5r4s2");
        b5r4s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r4s2ActionPerformed(evt);
            }
        });
        add(b5r4s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 792, 65, 23));

        b5r5s1.setErrorlist(errorList);
        b5r5s1.setNextFocusableComponent(b5r5s2);
        b5r5s1.setPanel(this);
        b5r5s1.setPosition(193);
        b5r5s1.setVarName("b5r5s1");
        b5r5s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r5s1ActionPerformed(evt);
            }
        });
        add(b5r5s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 838, 23, 23));

        b5r5s2.setErrorlist(errorList);
        b5r5s2.setNextFocusableComponent(b5r6);
        b5r5s2.setPanel(this);
        b5r5s2.setPosition(194);
        b5r5s2.setVarName("b5r5s2");
        b5r5s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r5s2ActionPerformed(evt);
            }
        });
        add(b5r5s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 870, 65, 23));

        b5r6.setErrorlist(errorList);
        b5r6.setNextFocusableComponent(b5r7);
        b5r6.setPanel(this);
        b5r6.setPosition(195);
        b5r6.setVarName("b5r6");
        b5r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r6ActionPerformed(evt);
            }
        });
        add(b5r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 925, 23, 23));

        b5r7.setErrorlist(errorList);
        b5r7.setNextpage(true);
        b5r7.setPanel(this);
        b5r7.setPosition(196);
        b5r7.setVarName("b5r7");
        b5r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5r7ActionPerformed(evt);
            }
        });
        add(b5r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 985, 23, 23));

        Halaman4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/us4.png"))); // NOI18N
        add(Halaman4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void b5r3s1t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t4ActionPerformed

    private void b5r1s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r1s4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r1s4ActionPerformed

    private void b5r1s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r1s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r1s5ActionPerformed

    private void b5r1s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r1s6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r1s6ActionPerformed

    private void b5r1s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r1s7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r1s7ActionPerformed

    private void b5r2s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r2s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r2s1ActionPerformed

    private void b5r2s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r2s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r2s2ActionPerformed

    private void b5r2s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r2s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r2s3ActionPerformed

    private void b5r3s1t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t1x1ActionPerformed

    private void b5r3s1t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t1x2ActionPerformed

    private void b5r3s1t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t2x1ActionPerformed

    private void b5r3s1t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t2x2ActionPerformed

    private void b5r3s1t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t3x1ActionPerformed

    private void b5r3s1t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s1t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s1t3x2ActionPerformed

    private void b5r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r7ActionPerformed

    private void b5r4s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r4s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r4s1ActionPerformed

    private void b5r4s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r4s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r4s2ActionPerformed

    private void b5r5s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r5s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r5s1ActionPerformed

    private void b5r5s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r5s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r5s2ActionPerformed

    private void b5r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r6ActionPerformed

    private void b5r3s2t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t1x1ActionPerformed

    private void b5r3s2t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t1x2ActionPerformed

    private void b5r3s2t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t2x1ActionPerformed

    private void b5r3s2t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t2x2ActionPerformed

    private void b5r3s2t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t3x1ActionPerformed

    private void b5r3s2t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t3x2ActionPerformed

    private void b5r3s2t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s2t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s2t4ActionPerformed

    private void b5r3s3t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t1x1ActionPerformed

    private void b5r3s3t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t1x2ActionPerformed

    private void b5r3s3t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t2x1ActionPerformed

    private void b5r3s3t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t2x2ActionPerformed

    private void b5r3s3t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t3x1ActionPerformed

    private void b5r3s3t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t3x2ActionPerformed

    private void b5r3s3t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s3t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s3t4ActionPerformed

    private void b5r3s4t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t1x1ActionPerformed

    private void b5r3s4t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t1x2ActionPerformed

    private void b5r3s4t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t2x1ActionPerformed

    private void b5r3s4t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t2x2ActionPerformed

    private void b5r3s4t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t3x1ActionPerformed

    private void b5r3s4t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t3x2ActionPerformed

    private void b5r3s4t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s4t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s4t4ActionPerformed

    private void b5r3s5t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t1x1ActionPerformed

    private void b5r3s5t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t1x2ActionPerformed

    private void b5r3s5t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t2x1ActionPerformed

    private void b5r3s5t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t2x2ActionPerformed

    private void b5r3s5t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t3x1ActionPerformed

    private void b5r3s5t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t3x2ActionPerformed

    private void b5r3s5t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s5t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s5t4ActionPerformed

    private void b5r3s6t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t1x1ActionPerformed

    private void b5r3s6t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t1x2ActionPerformed

    private void b5r3s6t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t2x1ActionPerformed

    private void b5r3s6t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t2x2ActionPerformed

    private void b5r3s6t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t3x1ActionPerformed

    private void b5r3s6t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t3x2ActionPerformed

    private void b5r3s6t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s6t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s6t4ActionPerformed

    private void b5r3s7t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t1x1ActionPerformed

    private void b5r3s7t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t1x2ActionPerformed

    private void b5r3s7t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t2x1ActionPerformed

    private void b5r3s7t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t2x2ActionPerformed

    private void b5r3s7t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t3x1ActionPerformed

    private void b5r3s7t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t3x2ActionPerformed

    private void b5r3s7t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s7t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s7t4ActionPerformed

    private void b5r3s8t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t1x1ActionPerformed

    private void b5r3s8t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t1x2ActionPerformed

    private void b5r3s8t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t2x1ActionPerformed

    private void b5r3s8t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t2x2ActionPerformed

    private void b5r3s8t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t3x1ActionPerformed

    private void b5r3s8t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t3x2ActionPerformed

    private void b5r3s8t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s8t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s8t4ActionPerformed

    private void b5r3s9t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t1x1ActionPerformed

    private void b5r3s9t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t1x2ActionPerformed

    private void b5r3s9t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t2x1ActionPerformed

    private void b5r3s9t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t2x2ActionPerformed

    private void b5r3s9t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t3x1ActionPerformed

    private void b5r3s9t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t3x2ActionPerformed

    private void b5r3s9t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s9t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s9t4ActionPerformed

    private void b5r3s10t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t1x1ActionPerformed

    private void b5r3s10t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t1x2ActionPerformed

    private void b5r3s10t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t2x1ActionPerformed

    private void b5r3s10t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t2x2ActionPerformed

    private void b5r3s10t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t3x1ActionPerformed

    private void b5r3s10t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t3x2ActionPerformed

    private void b5r3s10t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s10t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s10t4ActionPerformed

    private void b5r3s11t1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t1x1ActionPerformed

    private void b5r3s11t1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t1x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t1x2ActionPerformed

    private void b5r3s11t2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t2x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t2x1ActionPerformed

    private void b5r3s11t2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t2x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t2x2ActionPerformed

    private void b5r3s11t3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t3x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t3x1ActionPerformed

    private void b5r3s11t3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t3x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t3x2ActionPerformed

    private void b5r3s11t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5r3s11t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5r3s11t4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Halaman4;
    private pkl55.data.view.InputTextField b5r1s1;
    private pkl55.data.view.InputTextField b5r1s2;
    private pkl55.data.view.InputTextField b5r1s3;
    private pkl55.data.view.InputTextField b5r1s4;
    private pkl55.data.view.InputTextField b5r1s5;
    private pkl55.data.view.InputTextField b5r1s6;
    private pkl55.data.view.InputTextField b5r1s7;
    private pkl55.data.view.InputTextField b5r2s1;
    private pkl55.data.view.InputTextField b5r2s2;
    private pkl55.data.view.InputTextField b5r2s3;
    private pkl55.data.view.InputTextField b5r3s10t1x1;
    private pkl55.data.view.InputTextField b5r3s10t1x2;
    private pkl55.data.view.InputTextField b5r3s10t2x1;
    private pkl55.data.view.InputTextField b5r3s10t2x2;
    private pkl55.data.view.InputTextField b5r3s10t3x1;
    private pkl55.data.view.InputTextField b5r3s10t3x2;
    private pkl55.data.view.InputTextField b5r3s10t4;
    private pkl55.data.view.InputTextField b5r3s11t1x1;
    private pkl55.data.view.InputTextField b5r3s11t1x2;
    private pkl55.data.view.InputTextField b5r3s11t2x1;
    private pkl55.data.view.InputTextField b5r3s11t2x2;
    private pkl55.data.view.InputTextField b5r3s11t3x1;
    private pkl55.data.view.InputTextField b5r3s11t3x2;
    private pkl55.data.view.InputTextField b5r3s11t4;
    private pkl55.data.view.InputTextField b5r3s1t1x1;
    private pkl55.data.view.InputTextField b5r3s1t1x2;
    private pkl55.data.view.InputTextField b5r3s1t2x1;
    private pkl55.data.view.InputTextField b5r3s1t2x2;
    private pkl55.data.view.InputTextField b5r3s1t3x1;
    private pkl55.data.view.InputTextField b5r3s1t3x2;
    private pkl55.data.view.InputTextField b5r3s1t4;
    private pkl55.data.view.InputTextField b5r3s2t1x1;
    private pkl55.data.view.InputTextField b5r3s2t1x2;
    private pkl55.data.view.InputTextField b5r3s2t2x1;
    private pkl55.data.view.InputTextField b5r3s2t2x2;
    private pkl55.data.view.InputTextField b5r3s2t3x1;
    private pkl55.data.view.InputTextField b5r3s2t3x2;
    private pkl55.data.view.InputTextField b5r3s2t4;
    private pkl55.data.view.InputTextField b5r3s3t1x1;
    private pkl55.data.view.InputTextField b5r3s3t1x2;
    private pkl55.data.view.InputTextField b5r3s3t2x1;
    private pkl55.data.view.InputTextField b5r3s3t2x2;
    private pkl55.data.view.InputTextField b5r3s3t3x1;
    private pkl55.data.view.InputTextField b5r3s3t3x2;
    private pkl55.data.view.InputTextField b5r3s3t4;
    private pkl55.data.view.InputTextField b5r3s4t1x1;
    private pkl55.data.view.InputTextField b5r3s4t1x2;
    private pkl55.data.view.InputTextField b5r3s4t2x1;
    private pkl55.data.view.InputTextField b5r3s4t2x2;
    private pkl55.data.view.InputTextField b5r3s4t3x1;
    private pkl55.data.view.InputTextField b5r3s4t3x2;
    private pkl55.data.view.InputTextField b5r3s4t4;
    private pkl55.data.view.InputTextField b5r3s5t1x1;
    private pkl55.data.view.InputTextField b5r3s5t1x2;
    private pkl55.data.view.InputTextField b5r3s5t2x1;
    private pkl55.data.view.InputTextField b5r3s5t2x2;
    private pkl55.data.view.InputTextField b5r3s5t3x1;
    private pkl55.data.view.InputTextField b5r3s5t3x2;
    private pkl55.data.view.InputTextField b5r3s5t4;
    private pkl55.data.view.InputTextField b5r3s6t1x1;
    private pkl55.data.view.InputTextField b5r3s6t1x2;
    private pkl55.data.view.InputTextField b5r3s6t2x1;
    private pkl55.data.view.InputTextField b5r3s6t2x2;
    private pkl55.data.view.InputTextField b5r3s6t3x1;
    private pkl55.data.view.InputTextField b5r3s6t3x2;
    private pkl55.data.view.InputTextField b5r3s6t4;
    private pkl55.data.view.InputTextField b5r3s7t1x1;
    private pkl55.data.view.InputTextField b5r3s7t1x2;
    private pkl55.data.view.InputTextField b5r3s7t2x1;
    private pkl55.data.view.InputTextField b5r3s7t2x2;
    private pkl55.data.view.InputTextField b5r3s7t3x1;
    private pkl55.data.view.InputTextField b5r3s7t3x2;
    private pkl55.data.view.InputTextField b5r3s7t4;
    private pkl55.data.view.InputTextField b5r3s8t1x1;
    private pkl55.data.view.InputTextField b5r3s8t1x2;
    private pkl55.data.view.InputTextField b5r3s8t2x1;
    private pkl55.data.view.InputTextField b5r3s8t2x2;
    private pkl55.data.view.InputTextField b5r3s8t3x1;
    private pkl55.data.view.InputTextField b5r3s8t3x2;
    private pkl55.data.view.InputTextField b5r3s8t4;
    private pkl55.data.view.InputTextField b5r3s9t1x1;
    private pkl55.data.view.InputTextField b5r3s9t1x2;
    private pkl55.data.view.InputTextField b5r3s9t2x1;
    private pkl55.data.view.InputTextField b5r3s9t2x2;
    private pkl55.data.view.InputTextField b5r3s9t3x1;
    private pkl55.data.view.InputTextField b5r3s9t3x2;
    private pkl55.data.view.InputTextField b5r3s9t4;
    private pkl55.data.view.InputTextField b5r4s1;
    private pkl55.data.view.InputTextField b5r4s2;
    private pkl55.data.view.InputTextField b5r5s1;
    private pkl55.data.view.InputTextField b5r5s2;
    private pkl55.data.view.InputTextField b5r6;
    private pkl55.data.view.InputTextField b5r7;
    // End of variables declaration//GEN-END:variables
}
