/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import java.awt.Component;
import pkl55.data.view.Field;
import pkl55.data.view.Hal;

/**
 *
 * @author ItsFadrur
 */
public class UUHal6 extends Hal {

    /**
     * Creates new form ushal6
     */
    public UUHal6() {
        initComponents();
    }

    
    public void addToView(){
        for (Component comp : getComponents()) {
            if (comp.isVisible()) {
                if (comp instanceof Field) {
                    ((Field) comp).addToView();
                    ((Field) comp).setErrorlist(errorList);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b8r4 = new pkl55.data.view.InputTextField();
        b7r1s1 = new pkl55.data.view.InputTextField();
        b7r2s1 = new pkl55.data.view.InputTextField();
        b7r2s2 = new pkl55.data.view.InputTextField();
        b7r2s3 = new pkl55.data.view.InputTextField();
        b7r2s4 = new pkl55.data.view.InputTextField();
        b7r2s5 = new pkl55.data.view.InputTextField();
        b7r2s6 = new pkl55.data.view.InputTextField();
        b7r2s7 = new pkl55.data.view.InputTextField();
        b7r2s7lainnya = new pkl55.data.view.InputTextField();
        b7r3lainnya = new pkl55.data.view.InputTextField();
        b7r3 = new pkl55.data.view.InputTextField();
        b7r4 = new pkl55.data.view.InputTextField();
        b7r1s2 = new pkl55.data.view.InputTextField();
        b7r4lainnya = new pkl55.data.view.InputTextField();
        b8r1 = new pkl55.data.view.InputTextField();
        b8r2 = new pkl55.data.view.InputTextField();
        b8r3 = new pkl55.data.view.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(753, 1069));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b8r4.setErrorlist(errorList);
        b8r4.setNextpage(true);
        b8r4.setPanel(this);
        b8r4.setPosition(262);
        b8r4.setVarName("b8r4");
        b8r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8r4ActionPerformed(evt);
            }
        });
        add(b8r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 310, -1));

        b7r1s1.setErrorlist(errorList);
        b7r1s1.setNextFocusableComponent(b7r1s2);
        b7r1s1.setPanel(this);
        b7r1s1.setPosition(245);
        b7r1s1.setVarName("b7r1s1");
        add(b7r1s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 61, 67, 23));

        b7r2s1.setErrorlist(errorList);
        b7r2s1.setNextFocusableComponent(b7r2s2);
        b7r2s1.setPanel(this);
        b7r2s1.setPosition(247);
        b7r2s1.setVarName("b7r2s1");
        add(b7r2s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 132, 23, 23));

        b7r2s2.setErrorlist(errorList);
        b7r2s2.setNextFocusableComponent(b7r2s3);
        b7r2s2.setPanel(this);
        b7r2s2.setPosition(248);
        b7r2s2.setVarName("b7r2s2");
        add(b7r2s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 157, 23, 23));

        b7r2s3.setErrorlist(errorList);
        b7r2s3.setNextFocusableComponent(b7r2s4);
        b7r2s3.setPanel(this);
        b7r2s3.setPosition(249);
        b7r2s3.setVarName("b7r2s3");
        add(b7r2s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 182, 23, 23));

        b7r2s4.setErrorlist(errorList);
        b7r2s4.setNextFocusableComponent(b7r2s5);
        b7r2s4.setPanel(this);
        b7r2s4.setPosition(250);
        b7r2s4.setVarName("b7r2s4");
        add(b7r2s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 208, 23, 23));

        b7r2s5.setErrorlist(errorList);
        b7r2s5.setNextFocusableComponent(b7r2s6);
        b7r2s5.setPanel(this);
        b7r2s5.setPosition(251);
        b7r2s5.setVarName("b7r2s5");
        add(b7r2s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 233, 23, 23));

        b7r2s6.setErrorlist(errorList);
        b7r2s6.setNextFocusableComponent(b7r2s7);
        b7r2s6.setPanel(this);
        b7r2s6.setPosition(252);
        b7r2s6.setVarName("b7r2s6");
        add(b7r2s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 258, 23, 23));

        b7r2s7.setErrorlist(errorList);
        b7r2s7.setNextFocusableComponent(b7r2s7lainnya);
        b7r2s7.setPanel(this);
        b7r2s7.setPosition(253);
        b7r2s7.setVarName("b7r2s7");
        add(b7r2s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 284, 23, 23));

        b7r2s7lainnya.setErrorlist(errorList);
        b7r2s7lainnya.setNextFocusableComponent(b7r3);
        b7r2s7lainnya.setPanel(this);
        b7r2s7lainnya.setPosition(254);
        b7r2s7lainnya.setVarName("b7r2s7lainnya");
        add(b7r2s7lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 290, 170, -1));

        b7r3lainnya.setErrorlist(errorList);
        b7r3lainnya.setNextFocusableComponent(b7r4);
        b7r3lainnya.setPanel(this);
        b7r3lainnya.setPosition(256);
        b7r3lainnya.setVarName("b7r3lainnya");
        b7r3lainnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7r3lainnyaActionPerformed(evt);
            }
        });
        add(b7r3lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 170, -1));

        b7r3.setErrorlist(errorList);
        b7r3.setNextFocusableComponent(b7r3lainnya);
        b7r3.setPanel(this);
        b7r3.setPosition(255);
        b7r3.setVarName("b7r3");
        b7r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7r3ActionPerformed(evt);
            }
        });
        add(b7r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 351, 23, 23));

        b7r4.setErrorlist(errorList);
        b7r4.setNextFocusableComponent(b8r4);
        b7r4.setPanel(this);
        b7r4.setPosition(257);
        b7r4.setVarName("b7r4");
        b7r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7r4ActionPerformed(evt);
            }
        });
        add(b7r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 438, 23, 23));

        b7r1s2.setErrorlist(errorList);
        b7r1s2.setNextFocusableComponent(b7r2s1);
        b7r1s2.setPanel(this);
        b7r1s2.setPosition(246);
        b7r1s2.setVarName("b7r1s2");
        add(b7r1s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 67, 23));

        b7r4lainnya.setErrorlist(errorList);
        b7r4lainnya.setNextFocusableComponent(b8r1);
        b7r4lainnya.setPanel(this);
        b7r4lainnya.setPosition(258);
        b7r4lainnya.setVarName("b7r4lainnya");
        b7r4lainnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7r4lainnyaActionPerformed(evt);
            }
        });
        add(b7r4lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 465, 170, -1));

        b8r1.setErrorlist(errorList);
        b8r1.setNextFocusableComponent(b8r2);
        b8r1.setPanel(this);
        b8r1.setPosition(259);
        b8r1.setVarName("b8r1");
        b8r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8r1ActionPerformed(evt);
            }
        });
        add(b8r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 310, -1));

        b8r2.setErrorlist(errorList);
        b8r2.setNextFocusableComponent(b8r3);
        b8r2.setPanel(this);
        b8r2.setPosition(260);
        b8r2.setVarName("b8r2");
        b8r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8r2ActionPerformed(evt);
            }
        });
        add(b8r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 310, -1));

        b8r3.setErrorlist(errorList);
        b8r3.setNextFocusableComponent(b8r4);
        b8r3.setPanel(this);
        b8r3.setPosition(261);
        b8r3.setVarName("b8r3");
        b8r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8r3ActionPerformed(evt);
            }
        });
        add(b8r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/kuesioner/picture/us6.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void b8r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8r4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8r4ActionPerformed

    private void b7r3lainnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7r3lainnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7r3lainnyaActionPerformed

    private void b7r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7r3ActionPerformed

    private void b7r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7r4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7r4ActionPerformed

    private void b7r4lainnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7r4lainnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7r4lainnyaActionPerformed

    private void b8r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8r1ActionPerformed

    private void b8r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8r2ActionPerformed

    private void b8r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8r3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.data.view.InputTextField b7r1s1;
    private pkl55.data.view.InputTextField b7r1s2;
    private pkl55.data.view.InputTextField b7r2s1;
    private pkl55.data.view.InputTextField b7r2s2;
    private pkl55.data.view.InputTextField b7r2s3;
    private pkl55.data.view.InputTextField b7r2s4;
    private pkl55.data.view.InputTextField b7r2s5;
    private pkl55.data.view.InputTextField b7r2s6;
    private pkl55.data.view.InputTextField b7r2s7;
    private pkl55.data.view.InputTextField b7r2s7lainnya;
    private pkl55.data.view.InputTextField b7r3;
    private pkl55.data.view.InputTextField b7r3lainnya;
    private pkl55.data.view.InputTextField b7r4;
    private pkl55.data.view.InputTextField b7r4lainnya;
    private pkl55.data.view.InputTextField b8r1;
    private pkl55.data.view.InputTextField b8r2;
    private pkl55.data.view.InputTextField b8r3;
    private pkl55.data.view.InputTextField b8r4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
