/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.view;

import pkl55.data.view.Panel;

/**
 *
 * @author faqih_
 */
public class UUMainPanel extends Panel {

    /**
     * Creates new form UUMainPanel
     */
    public UUMainPanel() {
        pkl55.data.view.View.init(263);
        initComponents();
    }

    @Override
    public void init() {
        addToView(uUHal11,uUHal21,uUHal31,uUHal41,uUHal51,uUHal61,uUHal71);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uUHal11 = new pkl55.kuesioner.view.UUHal1();
        uUHal21 = new pkl55.kuesioner.view.UUHal2();
        uUHal31 = new pkl55.kuesioner.view.UUHal3();
        uUHal41 = new pkl55.kuesioner.view.UUHal4();
        uUHal51 = new pkl55.kuesioner.view.UUHal5();
        uUHal61 = new pkl55.kuesioner.view.UUHal6();
        uUHal71 = new pkl55.kuesioner.view.UUHal7();

        setLayout(new java.awt.CardLayout());
        add(uUHal11, "card2");
        add(uUHal21, "card3");
        add(uUHal31, "card4");
        add(uUHal41, "card5");
        add(uUHal51, "card6");
        add(uUHal61, "card7");
        add(uUHal71, "card8");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.kuesioner.view.UUHal1 uUHal11;
    private pkl55.kuesioner.view.UUHal2 uUHal21;
    private pkl55.kuesioner.view.UUHal3 uUHal31;
    private pkl55.kuesioner.view.UUHal4 uUHal41;
    private pkl55.kuesioner.view.UUHal5 uUHal51;
    private pkl55.kuesioner.view.UUHal6 uUHal61;
    private pkl55.kuesioner.view.UUHal7 uUHal71;
    // End of variables declaration//GEN-END:variables
}
