/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.gui.panel;

import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import pkl55.data.model.Model;
import pkl55.data.view.ErrorDetil;
import pkl55.data.view.ErrorList;
import pkl55.data.view.Field;
import pkl55.data.view.Panel;
import pkl55.gui.component.Called;
import pkl55.kuesioner.validasi.ValidasiLU;
import pkl55.kuesioner.validasi.ValidasiR;
import pkl55.kuesioner.validasi.ValidasiUU;
import pkl55.kuesioner.view.LUMainPanel;
import pkl55.kuesioner.view.RMainPanel;
import pkl55.kuesioner.view.UUMainPanel;
import pkl55.kuesioner.view.UUPanel;
import pkl55.main.MainFrame;

/**
 *
 * @author faqih_
 */
public class EntriPanel extends javax.swing.JPanel {

    private Panel kues;
    private ErrorList errorList;
    private ErrorDetil errorDetil;

    public EntriPanel() {
        initComponents();
    }

    public void setErrorPanel(ErrorList errorList, ErrorDetil errorDetil) {
        this.errorList = errorList;
        this.errorDetil = errorDetil;
        init();
    }

    public void init() {

        errorList.SetErrorDetil(errorDetil);
        saveButton.setClick(new Called() {
            @Override
            public void click() {
                Model.saveAll();
            }
        });
        nextButton.setClick(new Called() {
            @Override
            public void click() {
                kues.next();
            }
        });
        backButton.setClick(new Called() {
            @Override
            public void click() {
                kues.back();
            }
        });
        checkErrorButton.setClick(new Called() {
            @Override
            public void click() {
                for(Field fl: pkl55.data.view.View.list){
                    System.out.println(fl.varName);
                }
                if(!Model.checkAll()){
                    JOptionPane.showMessageDialog(MainFrame.getInstance(), "Masih Terdapat Validasi Yang Error");
                }
            }
        });
        exitButton.setClick(new Called() {
            @Override
            public void click() {
                int out = JOptionPane.showConfirmDialog(MainFrame.getInstance(), "Apakah Anda Ingin Keluar", "Perhatian", JOptionPane.OK_CANCEL_OPTION);
                if(out == 0){
                    MainFrame.getInstance().getMainPanel1().mainMenu();
                }
            }
        });
    }

    public static final int UU = new Random().nextInt();
    public static final int LU = new Random().nextInt();
    public static final int R = new Random().nextInt();

    public void setKues(int type) {
        kues = null;
        if (type == UU) {
            kues = new UUMainPanel();
            ValidasiUU.kuesioner();
        } else if (type == LU) {
            kues = new LUMainPanel();
            ValidasiLU.kuesioner();
        } else if (type == R) {
            kues = new RMainPanel();
            ValidasiR.kuesioner();
        }
        kues_panel.setViewportView(kues);
        kues.setErrorList(errorList);
        kues.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new pkl55.gui.component.BackButton();
        nextButton = new pkl55.gui.component.NextButton();
        saveButton = new pkl55.gui.component.SaveButton();
        exitButton = new pkl55.gui.component.ExitButton();
        checkErrorButton = new pkl55.gui.component.CheckErrorButton();
        kues_panel = new javax.swing.JScrollPane();
        page_button_box = new javax.swing.JPanel();
        background_image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));
        add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, -1));
        add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));

        checkErrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkErrorButtonMouseClicked(evt);
            }
        });
        add(checkErrorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, -1, -1));
        add(kues_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 770, 530));

        page_button_box.setBackground(new java.awt.Color(255, 255, 255));
        page_button_box.setOpaque(false);

        /*

        add(page_button_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 380));
        */
        add(page_button_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 120, 70, 380));

        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/gui/images/entri_background.png"))); // NOI18N
        add(background_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void checkErrorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkErrorButtonMouseClicked
        for(Field f : pkl55.data.view.View.list){
            System.out.println(f.varName);
        }
    }//GEN-LAST:event_checkErrorButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.gui.component.BackButton backButton;
    private javax.swing.JLabel background_image;
    private pkl55.gui.component.CheckErrorButton checkErrorButton;
    private pkl55.gui.component.ExitButton exitButton;
    private javax.swing.JScrollPane kues_panel;
    private pkl55.gui.component.NextButton nextButton;
    private javax.swing.JPanel page_button_box;
    private pkl55.gui.component.SaveButton saveButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the kues_panel
     */
    public JScrollPane getKues_panel() {
        return kues_panel;
    }

}
