/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.gui.panel;

import java.awt.Color;
import javax.swing.ImageIcon;
import pkl55.gui.component.Called;

/**
 *
 * @author faqih_
 */
public class Help extends javax.swing.JPanel {

    private String hal[] = {
        "/pkl55/gui/images/memulai_program.png",
        "/pkl55/gui/images/mengakhiri_program.png",
        "/pkl55/gui/images/perlakuan_error.png",
        "/pkl55/gui/images/entri_DLU_1.png",
        "/pkl55/gui/images/entri_pencacahan_1.png",
        "/pkl55/gui/images/edit_kuesioner.png"
    };
    private int active;
    
    public Help() {
        initComponents();
        active = 0;
    }
    
    public void next(){
        background_image.setLocation(0, 0);
        if(active<5){
            active++;
            background_image.setIcon(new ImageIcon(getClass().getResource(hal[active])));
        }
    }
    
    public void back(){
        background_image.setLocation(0, 0);
        if(active>0){
            active--;
            background_image.setIcon(new ImageIcon(getClass().getResource(hal[active])));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        background_image = new javax.swing.JLabel();
        backButton = new pkl55.gui.component.BackButton();
        nextButton = new pkl55.gui.component.NextButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setForeground(new java.awt.Color(255, 255, 255));
        scroll.setOpaque(false);
        scroll.getVerticalScrollBar().setBackground(new Color(192, 192, 128));

        background_image.setBackground(new java.awt.Color(255, 255, 255));
        background_image.setForeground(new java.awt.Color(255, 255, 255));
        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl55/gui/images/memulai_program.png"))); // NOI18N
        scroll.setViewportView(background_image);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.gui.component.BackButton backButton;
    private javax.swing.JLabel background_image;
    private pkl55.gui.component.NextButton nextButton;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
