/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.helpPanelComponent;

/**
 *
 * @author nurilmi
 */
public class aHelpCard extends javax.swing.JPanel {

    /**
     * Creates new form aHelpCard
     */
    public aHelpCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainHelpPanel1 = new pkl55.helpPanelComponent.mainHelpPanel();
        entriCacahPanel1 = new pkl55.helpPanelComponent.entriCacahPanel();
        entriDSPanel1 = new pkl55.helpPanelComponent.entriDSPanel();
        errorKuesPanel1 = new pkl55.helpPanelComponent.errorKuesPanel();
        errorPenyimpananPanel1 = new pkl55.helpPanelComponent.errorPenyimpananPanel();
        kuesCacahPanel1 = new pkl55.helpPanelComponent.kuesCacahPanel();
        kuesDSPanel1 = new pkl55.helpPanelComponent.kuesDSPanel();
        memulaiProgramPanel1 = new pkl55.helpPanelComponent.memulaiProgramPanel();
        mengakhiriProgramPanel1 = new pkl55.helpPanelComponent.mengakhiriProgramPanel();
        missingValuePanel1 = new pkl55.helpPanelComponent.missingValuePanel();
        perlakuanErrorPanel1 = new pkl55.helpPanelComponent.perlakuanErrorPanel();
        petunjukPanel1 = new pkl55.helpPanelComponent.petunjukPanel();
        ruleValidasiPanel1 = new pkl55.helpPanelComponent.ruleValidasiPanel();
        updatingCacahPanel1 = new pkl55.helpPanelComponent.updatingCacahPanel();

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(mainHelpPanel1, "mainHelp");
        mainPanel.add(entriCacahPanel1, "entriKuesCacah");
        mainPanel.add(entriDSPanel1, "entriDSIsi");
        mainPanel.add(errorKuesPanel1, "errorKues");
        mainPanel.add(errorPenyimpananPanel1, "errorPenyimpanan");
        mainPanel.add(kuesCacahPanel1, "kuesCacah");
        mainPanel.add(kuesDSPanel1, "kuesDS");
        mainPanel.add(memulaiProgramPanel1, "memulaiProgram");
        mainPanel.add(mengakhiriProgramPanel1, "mengakhiriProgram");
        mainPanel.add(missingValuePanel1, "missingValue");
        mainPanel.add(perlakuanErrorPanel1, "perlakuanError");
        mainPanel.add(petunjukPanel1, "petunjuk");
        mainPanel.add(ruleValidasiPanel1, "ruleValidasi");
        mainPanel.add(updatingCacahPanel1, "updatingKues");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.helpPanelComponent.entriCacahPanel entriCacahPanel1;
    private pkl55.helpPanelComponent.entriDSPanel entriDSPanel1;
    private pkl55.helpPanelComponent.errorKuesPanel errorKuesPanel1;
    private pkl55.helpPanelComponent.errorPenyimpananPanel errorPenyimpananPanel1;
    private pkl55.helpPanelComponent.kuesCacahPanel kuesCacahPanel1;
    private pkl55.helpPanelComponent.kuesDSPanel kuesDSPanel1;
    private pkl55.helpPanelComponent.mainHelpPanel mainHelpPanel1;
    private javax.swing.JPanel mainPanel;
    private pkl55.helpPanelComponent.memulaiProgramPanel memulaiProgramPanel1;
    private pkl55.helpPanelComponent.mengakhiriProgramPanel mengakhiriProgramPanel1;
    private pkl55.helpPanelComponent.missingValuePanel missingValuePanel1;
    private pkl55.helpPanelComponent.perlakuanErrorPanel perlakuanErrorPanel1;
    private pkl55.helpPanelComponent.petunjukPanel petunjukPanel1;
    private pkl55.helpPanelComponent.ruleValidasiPanel ruleValidasiPanel1;
    private pkl55.helpPanelComponent.updatingCacahPanel updatingCacahPanel1;
    // End of variables declaration//GEN-END:variables

    public pkl55.helpPanelComponent.entriCacahPanel getEntriCacahPanel1() {
        return entriCacahPanel1;
    }

    public void setEntriCacahPanel1(pkl55.helpPanelComponent.entriCacahPanel entriCacahPanel1) {
        this.entriCacahPanel1 = entriCacahPanel1;
    }

    public pkl55.helpPanelComponent.entriDSPanel getEntriDSPanel1() {
        return entriDSPanel1;
    }

    public void setEntriDSPanel1(pkl55.helpPanelComponent.entriDSPanel entriDSPanel1) {
        this.entriDSPanel1 = entriDSPanel1;
    }

    public pkl55.helpPanelComponent.errorKuesPanel getErrorKuesPanel1() {
        return errorKuesPanel1;
    }

    public void setErrorKuesPanel1(pkl55.helpPanelComponent.errorKuesPanel errorKuesPanel1) {
        this.errorKuesPanel1 = errorKuesPanel1;
    }

    public pkl55.helpPanelComponent.errorPenyimpananPanel getErrorPenyimpananPanel1() {
        return errorPenyimpananPanel1;
    }

    public void setErrorPenyimpananPanel1(pkl55.helpPanelComponent.errorPenyimpananPanel errorPenyimpananPanel1) {
        this.errorPenyimpananPanel1 = errorPenyimpananPanel1;
    }

    public pkl55.helpPanelComponent.kuesCacahPanel getKuesCacahPanel1() {
        return kuesCacahPanel1;
    }

    public void setKuesCacahPanel1(pkl55.helpPanelComponent.kuesCacahPanel kuesCacahPanel1) {
        this.kuesCacahPanel1 = kuesCacahPanel1;
    }

    public pkl55.helpPanelComponent.kuesDSPanel getKuesDSPanel1() {
        return kuesDSPanel1;
    }

    public void setKuesDSPanel1(pkl55.helpPanelComponent.kuesDSPanel kuesDSPanel1) {
        this.kuesDSPanel1 = kuesDSPanel1;
    }

    public pkl55.helpPanelComponent.mainHelpPanel getMainHelpPanel1() {
        return mainHelpPanel1;
    }

    public void setMainHelpPanel1(pkl55.helpPanelComponent.mainHelpPanel mainHelpPanel1) {
        this.mainHelpPanel1 = mainHelpPanel1;
    }

    public javax.swing.JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(javax.swing.JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    public pkl55.helpPanelComponent.memulaiProgramPanel getMemulaiProgramPanel1() {
        return memulaiProgramPanel1;
    }

    public void setMemulaiProgramPanel1(pkl55.helpPanelComponent.memulaiProgramPanel memulaiProgramPanel1) {
        this.memulaiProgramPanel1 = memulaiProgramPanel1;
    }

    public pkl55.helpPanelComponent.mengakhiriProgramPanel getMengakhiriProgramPanel1() {
        return mengakhiriProgramPanel1;
    }

    public void setMengakhiriProgramPanel1(pkl55.helpPanelComponent.mengakhiriProgramPanel mengakhiriProgramPanel1) {
        this.mengakhiriProgramPanel1 = mengakhiriProgramPanel1;
    }

    public pkl55.helpPanelComponent.missingValuePanel getMissingValuePanel1() {
        return missingValuePanel1;
    }

    public void setMissingValuePanel1(pkl55.helpPanelComponent.missingValuePanel missingValuePanel1) {
        this.missingValuePanel1 = missingValuePanel1;
    }

    public pkl55.helpPanelComponent.perlakuanErrorPanel getPerlakuanErrorPanel1() {
        return perlakuanErrorPanel1;
    }

    public void setPerlakuanErrorPanel1(pkl55.helpPanelComponent.perlakuanErrorPanel perlakuanErrorPanel1) {
        this.perlakuanErrorPanel1 = perlakuanErrorPanel1;
    }

    public pkl55.helpPanelComponent.petunjukPanel getPetunjukPanel1() {
        return petunjukPanel1;
    }

    public void setPetunjukPanel1(pkl55.helpPanelComponent.petunjukPanel petunjukPanel1) {
        this.petunjukPanel1 = petunjukPanel1;
    }

    public pkl55.helpPanelComponent.ruleValidasiPanel getRuleValidasiPanel1() {
        return ruleValidasiPanel1;
    }

    public void setRuleValidasiPanel1(pkl55.helpPanelComponent.ruleValidasiPanel ruleValidasiPanel1) {
        this.ruleValidasiPanel1 = ruleValidasiPanel1;
    }

    public pkl55.helpPanelComponent.updatingCacahPanel getUpdatingCacahPanel1() {
        return updatingCacahPanel1;
    }

    public void setUpdatingCacahPanel1(pkl55.helpPanelComponent.updatingCacahPanel updatingCacahPanel1) {
        this.updatingCacahPanel1 = updatingCacahPanel1;
    }
}
