/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.helpPanelComponent;

/**
 *
 * @author nurilmi
 */
public class errorPenyimpananPanel extends javax.swing.JPanel {

    /**
     * Creates new form errorPenyimpananPanel
     */
    public errorPenyimpananPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorPenyimpananIsi1 = new pkl55.background3.errorPenyimpananIsi();
        backBt1 = new pkl55.component3.backBt();

        errorPenyimpananIsi1.setLayout(null);

        backBt1.setText("");
        backBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBt1ActionPerformed(evt);
            }
        });
        errorPenyimpananIsi1.add(backBt1);
        backBt1.setBounds(999, 530, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPenyimpananIsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPenyimpananIsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.component3.backBt backBt1;
    private pkl55.background3.errorPenyimpananIsi errorPenyimpananIsi1;
    // End of variables declaration//GEN-END:variables

    public pkl55.component3.backBt getBackBt1() {
        return backBt1;
    }

    public void setBackBt1(pkl55.component3.backBt backBt1) {
        this.backBt1 = backBt1;
    }

    public pkl55.background3.errorPenyimpananIsi getErrorPenyimpananIsi1() {
        return errorPenyimpananIsi1;
    }

    public void setErrorPenyimpananIsi1(pkl55.background3.errorPenyimpananIsi errorPenyimpananIsi1) {
        this.errorPenyimpananIsi1 = errorPenyimpananIsi1;
    }
}
