/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.helpPanelComponent;

/**
 *
 * @author nurilmi
 */
public class mainHelpPanel extends javax.swing.JPanel {

    /**
     * Creates new form mainHelpPanel
     */
    public mainHelpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainHelp1 = new pkl55.background3.mainHelp();
        petunjukBt1 = new pkl55.component3.petunjukBt();
        ruleValidasiBt1 = new pkl55.component3.ruleValidasiBt();
        perlakuanErrorBt1 = new pkl55.component3.perlakuanErrorBt();

        mainHelp1.setLayout(null);

        petunjukBt1.setText("");
        petunjukBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petunjukBt1ActionPerformed(evt);
            }
        });
        mainHelp1.add(petunjukBt1);
        petunjukBt1.setBounds(270, 210, 700, 50);

        ruleValidasiBt1.setText("");
        ruleValidasiBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleValidasiBt1ActionPerformed(evt);
            }
        });
        mainHelp1.add(ruleValidasiBt1);
        ruleValidasiBt1.setBounds(270, 300, 700, 50);

        perlakuanErrorBt1.setText("");
        perlakuanErrorBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perlakuanErrorBt1ActionPerformed(evt);
            }
        });
        mainHelp1.add(perlakuanErrorBt1);
        perlakuanErrorBt1.setBounds(270, 390, 700, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void petunjukBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petunjukBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petunjukBt1ActionPerformed

    private void ruleValidasiBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruleValidasiBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruleValidasiBt1ActionPerformed

    private void perlakuanErrorBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perlakuanErrorBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perlakuanErrorBt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.background3.mainHelp mainHelp1;
    private pkl55.component3.perlakuanErrorBt perlakuanErrorBt1;
    private pkl55.component3.petunjukBt petunjukBt1;
    private pkl55.component3.ruleValidasiBt ruleValidasiBt1;
    // End of variables declaration//GEN-END:variables

    public pkl55.background3.mainHelp getMainHelp1() {
        return mainHelp1;
    }

    public void setMainHelp1(pkl55.background3.mainHelp mainHelp1) {
        this.mainHelp1 = mainHelp1;
    }

    public pkl55.component3.perlakuanErrorBt getPerlakuanErrorBt1() {
        return perlakuanErrorBt1;
    }

    public void setPerlakuanErrorBt1(pkl55.component3.perlakuanErrorBt perlakuanErrorBt1) {
        this.perlakuanErrorBt1 = perlakuanErrorBt1;
    }

    public pkl55.component3.petunjukBt getPetunjukBt1() {
        return petunjukBt1;
    }

    public void setPetunjukBt1(pkl55.component3.petunjukBt petunjukBt1) {
        this.petunjukBt1 = petunjukBt1;
    }

    public pkl55.component3.ruleValidasiBt getRuleValidasiBt1() {
        return ruleValidasiBt1;
    }

    public void setRuleValidasiBt1(pkl55.component3.ruleValidasiBt ruleValidasiBt1) {
        this.ruleValidasiBt1 = ruleValidasiBt1;
    }
}
