/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.helpPanelComponent;

/**
 *
 * @author nurilmi
 */
public class petunjukPanel extends javax.swing.JPanel {

    /**
     * Creates new form petunjukPanel
     */
    public petunjukPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petunjukBg1 = new pkl55.background3.petunjukBg();
        memulaiProgramBt1 = new pkl55.component3.memulaiProgramBt();
        entriDSBt1 = new pkl55.component3.entriDSBt();
        entriCacahBt1 = new pkl55.component3.entriCacahBt();
        updatingKuesCacahBt1 = new pkl55.component3.updatingKuesCacahBt();
        mengakhiriProgramBt1 = new pkl55.component3.mengakhiriProgramBt();
        backBt2 = new pkl55.component3.backBt();

        petunjukBg1.setLayout(null);

        memulaiProgramBt1.setText("");
        memulaiProgramBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memulaiProgramBt1ActionPerformed(evt);
            }
        });
        petunjukBg1.add(memulaiProgramBt1);
        memulaiProgramBt1.setBounds(270, 160, 700, 50);

        entriDSBt1.setText("");
        entriDSBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriDSBt1ActionPerformed(evt);
            }
        });
        petunjukBg1.add(entriDSBt1);
        entriDSBt1.setBounds(270, 230, 700, 50);

        entriCacahBt1.setText("");
        entriCacahBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriCacahBt1ActionPerformed(evt);
            }
        });
        petunjukBg1.add(entriCacahBt1);
        entriCacahBt1.setBounds(270, 300, 700, 50);

        updatingKuesCacahBt1.setText("");
        updatingKuesCacahBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatingKuesCacahBt1ActionPerformed(evt);
            }
        });
        petunjukBg1.add(updatingKuesCacahBt1);
        updatingKuesCacahBt1.setBounds(270, 370, 700, 50);

        mengakhiriProgramBt1.setText("");
        mengakhiriProgramBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mengakhiriProgramBt1ActionPerformed(evt);
            }
        });
        petunjukBg1.add(mengakhiriProgramBt1);
        mengakhiriProgramBt1.setBounds(270, 440, 700, 50);

        backBt2.setText("");
        backBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBt2ActionPerformed(evt);
            }
        });
        petunjukBg1.add(backBt2);
        backBt2.setBounds(1000, 530, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petunjukBg1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petunjukBg1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void memulaiProgramBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memulaiProgramBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memulaiProgramBt1ActionPerformed

    private void entriDSBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriDSBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entriDSBt1ActionPerformed

    private void entriCacahBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriCacahBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entriCacahBt1ActionPerformed

    private void updatingKuesCacahBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatingKuesCacahBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatingKuesCacahBt1ActionPerformed

    private void mengakhiriProgramBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mengakhiriProgramBt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mengakhiriProgramBt1ActionPerformed

    private void backBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBt2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.component3.backBt backBt2;
    private pkl55.component3.entriCacahBt entriCacahBt1;
    private pkl55.component3.entriDSBt entriDSBt1;
    private pkl55.component3.memulaiProgramBt memulaiProgramBt1;
    private pkl55.component3.mengakhiriProgramBt mengakhiriProgramBt1;
    private pkl55.background3.petunjukBg petunjukBg1;
    private pkl55.component3.updatingKuesCacahBt updatingKuesCacahBt1;
    // End of variables declaration//GEN-END:variables

   

    public pkl55.component3.entriCacahBt getEntriCacahBt1() {
        return entriCacahBt1;
    }

    public void setEntriCacahBt1(pkl55.component3.entriCacahBt entriCacahBt1) {
        this.entriCacahBt1 = entriCacahBt1;
    }

    public pkl55.component3.entriDSBt getEntriDSBt1() {
        return entriDSBt1;
    }

    public void setEntriDSBt1(pkl55.component3.entriDSBt entriDSBt1) {
        this.entriDSBt1 = entriDSBt1;
    }

    public pkl55.component3.memulaiProgramBt getMemulaiProgramBt1() {
        return memulaiProgramBt1;
    }

    public void setMemulaiProgramBt1(pkl55.component3.memulaiProgramBt memulaiProgramBt1) {
        this.memulaiProgramBt1 = memulaiProgramBt1;
    }

    public pkl55.component3.mengakhiriProgramBt getMengakhiriProgramBt1() {
        return mengakhiriProgramBt1;
    }

    public void setMengakhiriProgramBt1(pkl55.component3.mengakhiriProgramBt mengakhiriProgramBt1) {
        this.mengakhiriProgramBt1 = mengakhiriProgramBt1;
    }

    public pkl55.background3.petunjukBg getPetunjukBg1() {
        return petunjukBg1;
    }

    public void setPetunjukBg1(pkl55.background3.petunjukBg petunjukBg1) {
        this.petunjukBg1 = petunjukBg1;
    }

    public pkl55.component3.updatingKuesCacahBt getUpdatingKuesCacahBt1() {
        return updatingKuesCacahBt1;
    }

    public void setUpdatingKuesCacahBt1(pkl55.component3.updatingKuesCacahBt updatingKuesCacahBt1) {
        this.updatingKuesCacahBt1 = updatingKuesCacahBt1;
    }

    public pkl55.component3.backBt getBackBt2() {
        return backBt2;
    }

    public void setBackBt2(pkl55.component3.backBt backBt2) {
        this.backBt2 = backBt2;
    }
}
