/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.maintest;

import java.awt.Image;
import javax.swing.ImageIcon;
import pkl55.controller.DSController;
import pkl55.controller.EntryKuesController;
import pkl55.controller.LoginPanelController;
import pkl55.model.EntryKuesModel;
import pkl55.model.LoginPanelModel;

/**
 *
 * @author _muh.shamad
 */
public class DataEntry55 extends javax.swing.JFrame {

    /**
     * Creates new form DataEntry55
     */
    private static DataEntry55 instance;

    public static void setInstance(DataEntry55 aInstance) {
        instance = aInstance;
    }
    private Image image;
    private LoginPanelController loginPanelController;
    private EntryKuesController entryKuesController;
    private LoginPanelModel loginPanelModel;
    private EntryKuesModel entryKuesModel;
    private DSController dSController;

    public DataEntry55() {
        initComponents();
        //instance = new DataEntry55();
        //navbarButton1.getHomebutton1().setActive(true);
        loginPanelModel = new LoginPanelModel();
        loginPanelController = new LoginPanelController(getMainPanel(), getGeneralPanel1(), getLoginPanel1(), getLoginPanelModel());
        entryKuesController = new EntryKuesController(getEntryKues1(), getEntryKuesModel(), getLoginPanelController(), generalPanel1.getKuesSubPanel1());
        dSController = new DSController(loginPanelController ,entryDSPanel1, generalPanel1.getdSSubPanel1());
        


        image = new ImageIcon(getClass().getResource("/pkl55/images/kuesioner.png")).getImage();
        setIconImage(image);
        //fullscreen Frame
        dispose();
        setUndecorated(true);
        setResizable(false);
        setVisible(true);
    }

    public static DataEntry55 getInstance() {
        if (instance == null) {
            instance = new DataEntry55();
        }
        return instance;
    }

    public void minim() {
        this.setState(ICONIFIED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel1 = new pkl55.panelcomponent.LoginPanel();
        generalPanel1 = new pkl55.panelcomponent.GeneralPanel();
        entryKues1 = new pkl55.panelcomponent.EntryKuesPanel();
        entryDSPanel1 = new pkl55.panelcomponent.EntryDSPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPanel1MouseClicked(evt);
            }
        });
        mainPanel.add(loginPanel1, "loginpanel");
        mainPanel.add(generalPanel1, "generalpanel");
        mainPanel.add(entryKues1, "entrykues");
        mainPanel.add(entryDSPanel1, "entryds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntry55.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntry55.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntry55.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntry55.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setInstance(new DataEntry55());
                getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.panelcomponent.EntryDSPanel entryDSPanel1;
    private pkl55.panelcomponent.EntryKuesPanel entryKues1;
    private pkl55.panelcomponent.GeneralPanel generalPanel1;
    private pkl55.panelcomponent.LoginPanel loginPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public LoginPanelController getLoginPanelController() {
        return loginPanelController;
    }

    public void setLoginPanelController(LoginPanelController loginPanelController) {
        this.loginPanelController = loginPanelController;
    }

    public EntryKuesController getEntryKuesController() {
        return entryKuesController;
    }

    public void setEntryKuesController(EntryKuesController entryKuesController) {
        this.entryKuesController = entryKuesController;
    }

    public LoginPanelModel getLoginPanelModel() {
        return loginPanelModel;
    }

    public void setLoginPanelModel(LoginPanelModel loginPanelModel) {
        this.loginPanelModel = loginPanelModel;
    }

    public EntryKuesModel getEntryKuesModel() {
        return entryKuesModel;
    }

    public void setEntryKuesModel(EntryKuesModel entryKuesModel) {
        this.entryKuesModel = entryKuesModel;
    }

    public pkl55.panelcomponent.EntryKuesPanel getEntryKues1() {
        return entryKues1;
    }

    public void setEntryKues1(pkl55.panelcomponent.EntryKuesPanel entryKues1) {
        this.entryKues1 = entryKues1;
    }

    public pkl55.panelcomponent.GeneralPanel getGeneralPanel1() {
        return generalPanel1;
    }

    public void setGeneralPanel1(pkl55.panelcomponent.GeneralPanel generalPanel1) {
        this.generalPanel1 = generalPanel1;
    }

    public pkl55.panelcomponent.LoginPanel getLoginPanel1() {
        return loginPanel1;
    }

    public void setLoginPanel1(pkl55.panelcomponent.LoginPanel loginPanel1) {
        this.loginPanel1 = loginPanel1;
    }

    public javax.swing.JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(javax.swing.JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }
}
