/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SectionPane;

import View.Hal;

/**
 *
 * @author ItsFadrur
 */
public class Halaman3 extends Hal {

    /**
     * Creates new form Halaman3
     */
    public Halaman3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b4r7 = new View.InputTextField();
        b4r8 = new View.InputTextField();
        b4r8lainnya = new View.InputTextField();
        b4r9 = new View.InputTextField();
        b4r9lainnya = new View.InputTextField();
        b4r10s1 = new View.InputTextField();
        b4r10s2 = new View.InputTextField();
        b4r11s1 = new View.InputTextField();
        b4r11s2 = new View.InputTextField();
        b4r12 = new View.InputTextField();
        b4r13 = new View.InputTextField();
        b4r14s1d1 = new View.InputTextField();
        b4r14s1d2 = new View.InputTextField();
        b4r14s2d1 = new View.InputTextField();
        b4r14s2d2 = new View.InputTextField();
        b4r14s3d1 = new View.InputTextField();
        b4r14s3d2 = new View.InputTextField();
        b4r14s4d1 = new View.InputTextField();
        b4r14s4d2 = new View.InputTextField();
        b4r14s5d1 = new View.InputTextField();
        b4r14s5d2 = new View.InputTextField();
        b4r14s6d1 = new View.InputTextField();
        b4r14s6d2 = new View.InputTextField();
        b4r15s1d1 = new View.InputTextField();
        b4r15s1d2 = new View.InputTextField();
        b4r15s2d1 = new View.InputTextField();
        b4r15s2d2 = new View.InputTextField();
        b4r15s3d1 = new View.InputTextField();
        b4r15s3d2 = new View.InputTextField();
        b4r15s4d1 = new View.InputTextField();
        b4r15s4d2 = new View.InputTextField();
        b4r15s5d1 = new View.InputTextField();
        b4r15s5d2 = new View.InputTextField();
        b4r15s6d1 = new View.InputTextField();
        b4r15s6d2 = new View.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(753, 1069));
        setLayout(null);

        b4r7.setErrorlist(errorList);
        b4r7.setNextFocusableComponent(b4r8);
        b4r7.setPanel(this);
        b4r7.setPosition(35);
        b4r7.setVarName("b4r7");
        add(b4r7);
        b4r7.setBounds(341, 76, 20, 20);

        b4r8.setErrorlist(errorList);
        b4r8.setNextFocusableComponent(b4r8lainnya);
        b4r8.setPanel(this);
        b4r8.setPosition(36);
        b4r8.setVarName("b4r8");
        add(b4r8);
        b4r8.setBounds(341, 184, 20, 20);

        b4r8lainnya.setErrorlist(errorList);
        b4r8lainnya.setNextFocusableComponent(b4r9);
        b4r8lainnya.setPanel(this);
        b4r8lainnya.setPosition(37);
        b4r8lainnya.setVarName("b4r8lainnya");
        add(b4r8lainnya);
        b4r8lainnya.setBounds(240, 200, 40, 20);

        b4r9.setErrorlist(errorList);
        b4r9.setNextFocusableComponent(b4r9lainnya);
        b4r9.setPanel(this);
        b4r9.setPosition(38);
        b4r9.setVarName("b4r9");
        add(b4r9);
        b4r9.setBounds(341, 274, 20, 20);

        b4r9lainnya.setErrorlist(errorList);
        b4r9lainnya.setNextFocusableComponent(b4r10s1);
        b4r9lainnya.setPanel(this);
        b4r9lainnya.setPosition(39);
        b4r9lainnya.setVarName("b4r9lainnya");
        add(b4r9lainnya);
        b4r9lainnya.setBounds(240, 300, 40, 20);

        b4r10s1.setErrorlist(errorList);
        b4r10s1.setNextFocusableComponent(b4r10s2);
        b4r10s1.setPanel(this);
        b4r10s1.setPosition(40);
        b4r10s1.setVarName("b4r10s1");
        add(b4r10s1);
        b4r10s1.setBounds(670, 40, 50, 20);

        b4r10s2.setErrorlist(errorList);
        b4r10s2.setNextFocusableComponent(b4r11s2);
        b4r10s2.setPanel(this);
        b4r10s2.setPosition(41);
        b4r10s2.setVarName("b4r10s2");
        add(b4r10s2);
        b4r10s2.setBounds(670, 80, 50, 20);

        b4r11s1.setPosition(42);
        b4r11s1.setVarName("b4r11s1");
        add(b4r11s1);
        b4r11s1.setBounds(440, 160, 50, 20);

        b4r11s2.setErrorlist(errorList);
        b4r11s2.setNextFocusableComponent(b4r12);
        b4r11s2.setPanel(this);
        b4r11s2.setPosition(43);
        b4r11s2.setVarName("b4r11s2");
        add(b4r11s2);
        b4r11s2.setBounds(510, 158, 210, 20);

        b4r12.setErrorlist(errorList);
        b4r12.setNextFocusableComponent(b4r13);
        b4r12.setPanel(this);
        b4r12.setPosition(44);
        b4r12.setVarName("b4r12");
        add(b4r12);
        b4r12.setBounds(700, 210, 20, 20);

        b4r13.setErrorlist(errorList);
        b4r13.setNextFocusableComponent(b4r14s1d1);
        b4r13.setPanel(this);
        b4r13.setPosition(45);
        b4r13.setVarName("b4r13");
        add(b4r13);
        b4r13.setBounds(700, 280, 20, 20);

        b4r14s1d1.setErrorlist(errorList);
        b4r14s1d1.setNextFocusableComponent(b4r14s1d2);
        b4r14s1d1.setPanel(this);
        b4r14s1d1.setPosition(46);
        b4r14s1d1.setVarName("b4r14s1d1");
        add(b4r14s1d1);
        b4r14s1d1.setBounds(170, 400, 20, 20);

        b4r14s1d2.setErrorlist(errorList);
        b4r14s1d2.setNextFocusableComponent(b4r14s2d1);
        b4r14s1d2.setPanel(this);
        b4r14s1d2.setPosition(47);
        b4r14s1d2.setVarName("b4r14s1d2");
        add(b4r14s1d2);
        b4r14s1d2.setBounds(240, 390, 470, 20);

        b4r14s2d1.setErrorlist(errorList);
        b4r14s2d1.setNextFocusableComponent(b4r14s2d2);
        b4r14s2d1.setPanel(this);
        b4r14s2d1.setPosition(48);
        b4r14s2d1.setVarName("b4r14s2d1");
        add(b4r14s2d1);
        b4r14s2d1.setBounds(170, 470, 20, 20);

        b4r14s2d2.setErrorlist(errorList);
        b4r14s2d2.setNextFocusableComponent(b4r14s3d1);
        b4r14s2d2.setPanel(this);
        b4r14s2d2.setPosition(49);
        b4r14s2d2.setVarName("b4r14s2d2");
        add(b4r14s2d2);
        b4r14s2d2.setBounds(240, 460, 470, 20);

        b4r14s3d1.setErrorlist(errorList);
        b4r14s3d1.setNextFocusableComponent(b4r14s3d2);
        b4r14s3d1.setPanel(this);
        b4r14s3d1.setPosition(50);
        b4r14s3d1.setVarName("b4r14s3d1");
        add(b4r14s3d1);
        b4r14s3d1.setBounds(170, 540, 20, 20);

        b4r14s3d2.setErrorlist(errorList);
        b4r14s3d2.setNextFocusableComponent(b4r14s4d1);
        b4r14s3d2.setPanel(this);
        b4r14s3d2.setPosition(51);
        b4r14s3d2.setVarName("b4r14s3d2");
        add(b4r14s3d2);
        b4r14s3d2.setBounds(240, 530, 470, 20);

        b4r14s4d1.setErrorlist(errorList);
        b4r14s4d1.setNextFocusableComponent(b4r14s4d2);
        b4r14s4d1.setPanel(this);
        b4r14s4d1.setPosition(52);
        b4r14s4d1.setVarName("b4r14s4d1");
        add(b4r14s4d1);
        b4r14s4d1.setBounds(170, 620, 20, 20);

        b4r14s4d2.setErrorlist(errorList);
        b4r14s4d2.setNextFocusableComponent(b4r14s5d1);
        b4r14s4d2.setPanel(this);
        b4r14s4d2.setPosition(53);
        b4r14s4d2.setVarName("b4r14s4d2");
        add(b4r14s4d2);
        b4r14s4d2.setBounds(240, 610, 470, 20);

        b4r14s5d1.setErrorlist(errorList);
        b4r14s5d1.setNextFocusableComponent(b4r15s5d2);
        b4r14s5d1.setPanel(this);
        b4r14s5d1.setPosition(54);
        b4r14s5d1.setVarName("b4r14s5d1");
        add(b4r14s5d1);
        b4r14s5d1.setBounds(170, 690, 20, 20);

        b4r14s5d2.setErrorlist(errorList);
        b4r14s5d2.setNextFocusableComponent(b4r14s6d1);
        b4r14s5d2.setPanel(this);
        b4r14s5d2.setPosition(55);
        b4r14s5d2.setVarName("b4r14s5d2");
        add(b4r14s5d2);
        b4r14s5d2.setBounds(240, 680, 470, 20);

        b4r14s6d1.setErrorlist(errorList);
        b4r14s6d1.setNextFocusableComponent(b4r15s6d2);
        b4r14s6d1.setPanel(this);
        b4r14s6d1.setPosition(56);
        b4r14s6d1.setVarName("b4r14s6d1");
        add(b4r14s6d1);
        b4r14s6d1.setBounds(170, 760, 20, 20);

        b4r14s6d2.setErrorlist(errorList);
        b4r14s6d2.setNextFocusableComponent(b4r15s1d1);
        b4r14s6d2.setPanel(this);
        b4r14s6d2.setPosition(57);
        b4r14s6d2.setVarName("b4r14s6d2");
        add(b4r14s6d2);
        b4r14s6d2.setBounds(240, 750, 470, 20);

        b4r15s1d1.setErrorlist(errorList);
        b4r15s1d1.setNextFocusableComponent(b4r15s1d2);
        b4r15s1d1.setPanel(this);
        b4r15s1d1.setPosition(58);
        b4r15s1d1.setVarName("b4r15s1d1");
        add(b4r15s1d1);
        b4r15s1d1.setBounds(342, 886, 50, 20);

        b4r15s1d2.setErrorlist(errorList);
        b4r15s1d2.setNextFocusableComponent(b4r15s2d1);
        b4r15s1d2.setPanel(this);
        b4r15s1d2.setPosition(59);
        b4r15s1d2.setVarName("b4r15s1d2");
        add(b4r15s1d2);
        b4r15s1d2.setBounds(408, 886, 210, 20);

        b4r15s2d1.setErrorlist(errorList);
        b4r15s2d1.setNextFocusableComponent(b4r15s2d2);
        b4r15s2d1.setPanel(this);
        b4r15s2d1.setPosition(60);
        b4r15s2d1.setVarName("b4r15s2d1");
        add(b4r15s2d1);
        b4r15s2d1.setBounds(342, 910, 50, 20);

        b4r15s2d2.setErrorlist(errorList);
        b4r15s2d2.setNextFocusableComponent(b4r15s3d1);
        b4r15s2d2.setPanel(this);
        b4r15s2d2.setPosition(61);
        b4r15s2d2.setVarName("b4r15s2d2");
        add(b4r15s2d2);
        b4r15s2d2.setBounds(408, 910, 210, 20);

        b4r15s3d1.setErrorlist(errorList);
        b4r15s3d1.setNextFocusableComponent(b4r15s3d2);
        b4r15s3d1.setPanel(this);
        b4r15s3d1.setPosition(62);
        b4r15s3d1.setVarName("b4r15s3d1");
        add(b4r15s3d1);
        b4r15s3d1.setBounds(342, 933, 50, 20);

        b4r15s3d2.setErrorlist(errorList);
        b4r15s3d2.setNextFocusableComponent(b4r15s4d1);
        b4r15s3d2.setPanel(this);
        b4r15s3d2.setPosition(63);
        b4r15s3d2.setVarName("b4r15s3d2");
        add(b4r15s3d2);
        b4r15s3d2.setBounds(408, 933, 210, 20);

        b4r15s4d1.setErrorlist(errorList);
        b4r15s4d1.setNextFocusableComponent(b4r15s4d2);
        b4r15s4d1.setPanel(this);
        b4r15s4d1.setPosition(64);
        b4r15s4d1.setVarName("b4r15s4d1");
        add(b4r15s4d1);
        b4r15s4d1.setBounds(342, 956, 50, 20);

        b4r15s4d2.setErrorlist(errorList);
        b4r15s4d2.setNextFocusableComponent(b4r15s5d1);
        b4r15s4d2.setPanel(this);
        b4r15s4d2.setPosition(65);
        b4r15s4d2.setVarName("b4r15s4d2");
        add(b4r15s4d2);
        b4r15s4d2.setBounds(408, 956, 210, 20);

        b4r15s5d1.setErrorlist(errorList);
        b4r15s5d1.setNextFocusableComponent(b4r15s5d2);
        b4r15s5d1.setPanel(this);
        b4r15s5d1.setPosition(66);
        b4r15s5d1.setVarName("b4r15s5d1");
        add(b4r15s5d1);
        b4r15s5d1.setBounds(342, 979, 50, 20);

        b4r15s5d2.setErrorlist(errorList);
        b4r15s5d2.setNextFocusableComponent(b4r15s6d1);
        b4r15s5d2.setPanel(this);
        b4r15s5d2.setPosition(67);
        b4r15s5d2.setVarName("b4r15s5d2");
        add(b4r15s5d2);
        b4r15s5d2.setBounds(408, 979, 210, 20);

        b4r15s6d1.setErrorlist(errorList);
        b4r15s6d1.setNextFocusableComponent(b4r15s6d2);
        b4r15s6d1.setPanel(this);
        b4r15s6d1.setPosition(68);
        b4r15s6d1.setVarName("b4r15s6d1");
        add(b4r15s6d1);
        b4r15s6d1.setBounds(342, 1003, 50, 20);

        b4r15s6d2.setErrorlist(errorList);
        b4r15s6d2.setNextpage(true);
        b4r15s6d2.setPanel(this);
        b4r15s6d2.setPosition(69);
        b4r15s6d2.setVarName("b4r15s6d2");
        add(b4r15s6d2);
        b4r15s6d2.setBounds(408, 1003, 210, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SourceOfPicture/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 791, 1066);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.InputTextField b4r10s1;
    private View.InputTextField b4r10s2;
    private View.InputTextField b4r11s1;
    private View.InputTextField b4r11s2;
    private View.InputTextField b4r12;
    private View.InputTextField b4r13;
    private View.InputTextField b4r14s1d1;
    private View.InputTextField b4r14s1d2;
    private View.InputTextField b4r14s2d1;
    private View.InputTextField b4r14s2d2;
    private View.InputTextField b4r14s3d1;
    private View.InputTextField b4r14s3d2;
    private View.InputTextField b4r14s4d1;
    private View.InputTextField b4r14s4d2;
    private View.InputTextField b4r14s5d1;
    private View.InputTextField b4r14s5d2;
    private View.InputTextField b4r14s6d1;
    private View.InputTextField b4r14s6d2;
    private View.InputTextField b4r15s1d1;
    private View.InputTextField b4r15s1d2;
    private View.InputTextField b4r15s2d1;
    private View.InputTextField b4r15s2d2;
    private View.InputTextField b4r15s3d1;
    private View.InputTextField b4r15s3d2;
    private View.InputTextField b4r15s4d1;
    private View.InputTextField b4r15s4d2;
    private View.InputTextField b4r15s5d1;
    private View.InputTextField b4r15s5d2;
    private View.InputTextField b4r15s6d1;
    private View.InputTextField b4r15s6d2;
    private View.InputTextField b4r7;
    private View.InputTextField b4r8;
    private View.InputTextField b4r8lainnya;
    private View.InputTextField b4r9;
    private View.InputTextField b4r9lainnya;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
