/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SectionPane;

import View.Hal;

/**
 *
 * @author ItsFadrur
 */
public class Halaman4 extends Hal {

    /**
     * Creates new form Halaman4
     */
    public Halaman4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1r17s2 = new View.InputTextField();
        b1r17s1 = new View.InputTextField();
        b1r18s2 = new View.InputTextField();
        b4r16 = new View.InputTextField();
        b1r18s1 = new View.InputTextField();
        b1r18s3 = new View.InputTextField();
        b1r18s4 = new View.InputTextField();
        b1r18s5 = new View.InputTextField();
        b1r18s6 = new View.InputTextField();
        b1r18s7 = new View.InputTextField();
        b1r18s9 = new View.InputTextField();
        b1r18s8 = new View.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(753, 1069));
        setLayout(null);

        b1r17s2.setErrorlist(errorList);
        b1r17s2.setNextFocusableComponent(b1r18s1);
        b1r17s2.setPanel(this);
        b1r17s2.setPosition(72);
        b1r17s2.setVarName("b4r17s2");
        add(b1r17s2);
        b1r17s2.setBounds(500, 90, 220, 20);

        b1r17s1.setErrorlist(errorList);
        b1r17s1.setNextFocusableComponent(b1r17s2);
        b1r17s1.setPanel(this);
        b1r17s1.setPosition(71);
        b1r17s1.setVarName("b4r17s1");
        add(b1r17s1);
        b1r17s1.setBounds(430, 90, 50, 20);

        b1r18s2.setErrorlist(errorList);
        b1r18s2.setPanel(this);
        b1r18s2.setPosition(74);
        b1r18s2.setVarName("b1r18s2");
        add(b1r18s2);
        b1r18s2.setBounds(630, 232, 20, 20);

        b4r16.setErrorlist(errorList);
        b4r16.setNextFocusableComponent(b1r17s1);
        b4r16.setPanel(this);
        b4r16.setPosition(70);
        b4r16.setVarName("b4r16");
        add(b4r16);
        b4r16.setBounds(340, 70, 20, 20);

        b1r18s1.setErrorlist(errorList);
        b1r18s1.setPanel(this);
        b1r18s1.setPosition(73);
        b1r18s1.setVarName("b1r18s1");
        add(b1r18s1);
        b1r18s1.setBounds(630, 201, 20, 20);

        b1r18s3.setErrorlist(errorList);
        b1r18s3.setPanel(this);
        b1r18s3.setPosition(75);
        b1r18s3.setVarName("b1r18s3");
        add(b1r18s3);
        b1r18s3.setBounds(630, 264, 20, 20);

        b1r18s4.setErrorlist(errorList);
        b1r18s4.setPanel(this);
        b1r18s4.setPosition(76);
        b1r18s4.setVarName("b1r18s4");
        add(b1r18s4);
        b1r18s4.setBounds(630, 297, 20, 20);

        b1r18s5.setErrorlist(errorList);
        b1r18s5.setPanel(this);
        b1r18s5.setPosition(77);
        b1r18s5.setVarName("b1r18s5");
        add(b1r18s5);
        b1r18s5.setBounds(630, 330, 20, 20);

        b1r18s6.setErrorlist(errorList);
        b1r18s6.setPanel(this);
        b1r18s6.setPosition(78);
        b1r18s6.setVarName("b1r18s6");
        add(b1r18s6);
        b1r18s6.setBounds(630, 360, 20, 20);

        b1r18s7.setErrorlist(errorList);
        b1r18s7.setPanel(this);
        b1r18s7.setPosition(79);
        b1r18s7.setVarName("b1r18s7");
        add(b1r18s7);
        b1r18s7.setBounds(630, 393, 20, 20);

        b1r18s9.setErrorlist(errorList);
        b1r18s9.setPanel(this);
        b1r18s9.setPosition(81);
        b1r18s9.setVarName("b1r18s9");
        add(b1r18s9);
        b1r18s9.setBounds(630, 457, 20, 20);

        b1r18s8.setErrorlist(errorList);
        b1r18s8.setPanel(this);
        b1r18s8.setPosition(80);
        b1r18s8.setVarName("b1r18s8");
        add(b1r18s8);
        b1r18s8.setBounds(630, 425, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SourceOfPicture/4.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 761, 1077);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.InputTextField b1r17s1;
    private View.InputTextField b1r17s2;
    private View.InputTextField b1r18s1;
    private View.InputTextField b1r18s2;
    private View.InputTextField b1r18s3;
    private View.InputTextField b1r18s4;
    private View.InputTextField b1r18s5;
    private View.InputTextField b1r18s6;
    private View.InputTextField b1r18s7;
    private View.InputTextField b1r18s8;
    private View.InputTextField b1r18s9;
    private View.InputTextField b4r16;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
