/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SectionPane;

import View.Hal;

/**
 *
 * @author ItsFadrur
 */
public class Halaman2 extends Hal {

    /**
     * Creates new form Halaman2
     */
    public Halaman2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3r1 = new View.InputTextField();
        b3r2 = new View.InputTextField();
        b3r3 = new View.InputTextField();
        b3r4 = new View.InputTextField();
        b3r5 = new View.InputTextField();
        b3r6 = new View.InputTextField();
        b3r7 = new View.InputTextField();
        b3r8 = new View.InputTextField();
        b3r8lainnya = new View.InputTextField();
        b4r1s1 = new View.InputTextField();
        b4r1s1lainnya = new View.InputTextField();
        b4r1s2 = new View.InputTextField();
        b4r1s2lainnya = new View.InputTextField();
        b4r2 = new View.InputTextField();
        b4r2lainnya = new View.InputTextField();
        b4r3 = new View.InputTextField();
        b4r3lainnya = new View.InputTextField();
        b4r4 = new View.InputTextField();
        b4r5 = new View.InputTextField();
        b4r5lainnya = new View.InputTextField();
        b4r6 = new View.InputTextField();
        b4r6lainnya = new View.InputTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(753, 1069));
        setLayout(null);

        b3r1.setErrorlist(errorList);
        b3r1.setNextFocusableComponent(b3r2);
        b3r1.setPanel(this);
        b3r1.setPosition(13);
        b3r1.setVarName("b3r1");
        add(b3r1);
        b3r1.setBounds(30, 70, 330, 20);

        b3r2.setErrorlist(errorList);
        b3r2.setNextFocusableComponent(b3r3);
        b3r2.setPanel(this);
        b3r2.setPosition(14);
        b3r2.setVarName("b3r2");
        add(b3r2);
        b3r2.setBounds(310, 110, 50, 20);

        b3r3.setErrorlist(errorList);
        b3r3.setNextFocusableComponent(b3r4);
        b3r3.setPanel(this);
        b3r3.setPosition(15);
        b3r3.setVarName("b3r3");
        add(b3r3);
        b3r3.setBounds(339, 155, 20, 20);

        b3r4.setErrorlist(errorList);
        b3r4.setNextFocusableComponent(b3r5);
        b3r4.setPanel(this);
        b3r4.setPosition(16);
        b3r4.setVarName("b3r4");
        add(b3r4);
        b3r4.setBounds(339, 269, 20, 20);

        b3r5.setErrorlist(errorList);
        b3r5.setNextFocusableComponent(b3r6);
        b3r5.setPanel(this);
        b3r5.setPosition(17);
        b3r5.setVarName("b3r5");
        add(b3r5);
        b3r5.setBounds(339, 411, 20, 20);

        b3r6.setErrorlist(errorList);
        b3r6.setNextFocusableComponent(b3r7);
        b3r6.setPanel(this);
        b3r6.setPosition(18);
        b3r6.setVarName("b3r6");
        add(b3r6);
        b3r6.setBounds(672, 165, 50, 20);

        b3r7.setErrorlist(errorList);
        b3r7.setNextFocusableComponent(b3r8);
        b3r7.setPanel(this);
        b3r7.setPosition(19);
        b3r7.setVarName("b3r7");
        add(b3r7);
        b3r7.setBounds(702, 299, 20, 20);

        b3r8.setErrorlist(errorList);
        b3r8.setNextFocusableComponent(b3r8lainnya);
        b3r8.setPanel(this);
        b3r8.setPosition(20);
        b3r8.setVarName("b3r8");
        add(b3r8);
        b3r8.setBounds(702, 377, 20, 20);

        b3r8lainnya.setErrorlist(errorList);
        b3r8lainnya.setNextFocusableComponent(b4r1s1);
        b3r8lainnya.setPanel(this);
        b3r8lainnya.setPosition(21);
        b3r8lainnya.setVarName("b3r8lainnya");
        add(b3r8lainnya);
        b3r8lainnya.setBounds(560, 400, 60, 20);

        b4r1s1.setErrorlist(errorList);
        b4r1s1.setNextFocusableComponent(b4r1s1lainnya);
        b4r1s1.setPanel(this);
        b4r1s1.setPosition(22);
        b4r1s1.setVarName("b4r1s1");
        add(b4r1s1);
        b4r1s1.setBounds(342, 525, 20, 20);

        b4r1s1lainnya.setErrorlist(errorList);
        b4r1s1lainnya.setNextFocusableComponent(b4r1s2);
        b4r1s1lainnya.setPanel(this);
        b4r1s1lainnya.setPosition(23);
        b4r1s1lainnya.setVarName("b4r1s1lainnya");
        add(b4r1s1lainnya);
        b4r1s1lainnya.setBounds(190, 540, 90, 20);

        b4r1s2.setErrorlist(errorList);
        b4r1s2.setNextFocusableComponent(b4r1s2lainnya);
        b4r1s2.setPanel(this);
        b4r1s2.setPosition(24);
        b4r1s2.setVarName("b4r1s2");
        add(b4r1s2);
        b4r1s2.setBounds(342, 594, 20, 20);

        b4r1s2lainnya.setErrorlist(null);
        b4r1s2lainnya.setNextFocusableComponent(b4r2);
        b4r1s2lainnya.setPanel(null);
        b4r1s2lainnya.setPosition(25);
        b4r1s2lainnya.setVarName("b4r1s2lainnya");
        add(b4r1s2lainnya);
        b4r1s2lainnya.setBounds(200, 630, 80, 20);

        b4r2.setErrorlist(errorList);
        b4r2.setNextFocusableComponent(b4r2lainnya);
        b4r2.setPanel(this);
        b4r2.setPosition(26);
        b4r2.setVarName("b4r2");
        add(b4r2);
        b4r2.setBounds(312, 735, 50, 20);

        b4r2lainnya.setErrorlist(errorList);
        b4r2lainnya.setNextFocusableComponent(b4r3);
        b4r2lainnya.setPanel(this);
        b4r2lainnya.setPosition(27);
        b4r2lainnya.setVarName("b4r2lainnya");
        add(b4r2lainnya);
        b4r2lainnya.setBounds(180, 800, 100, 20);

        b4r3.setErrorlist(errorList);
        b4r3.setNextFocusableComponent(b4r3lainnya);
        b4r3.setPanel(this);
        b4r3.setPosition(28);
        b4r3.setVarName("b4r3");
        add(b4r3);
        b4r3.setBounds(312, 924, 50, 20);

        b4r3lainnya.setErrorlist(errorList);
        b4r3lainnya.setNextFocusableComponent(b4r4);
        b4r3lainnya.setPanel(this);
        b4r3lainnya.setPosition(29);
        b4r3lainnya.setVarName("b4r3lainnya");
        add(b4r3lainnya);
        b4r3lainnya.setBounds(190, 1020, 90, 20);

        b4r4.setErrorlist(errorList);
        b4r4.setNextFocusableComponent(b4r5);
        b4r4.setPanel(this);
        b4r4.setPosition(30);
        b4r4.setVarName("b4r4");
        add(b4r4);
        b4r4.setBounds(702, 507, 20, 20);

        b4r5.setErrorlist(errorList);
        b4r5.setNextFocusableComponent(b4r5lainnya);
        b4r5.setPanel(this);
        b4r5.setPosition(31);
        b4r5.setVarName("b4r5");
        add(b4r5);
        b4r5.setBounds(662, 634, 60, 20);

        b4r5lainnya.setErrorlist(errorList);
        b4r5lainnya.setNextFocusableComponent(b4r6);
        b4r5lainnya.setPanel(this);
        b4r5lainnya.setPosition(32);
        b4r5lainnya.setVarName("b4r5lainnya");
        add(b4r5lainnya);
        b4r5lainnya.setBounds(490, 720, 140, 20);

        b4r6.setErrorlist(errorList);
        b4r6.setNextFocusableComponent(b4r6lainnya);
        b4r6.setPanel(this);
        b4r6.setPosition(33);
        b4r6.setVarName("b4r6");
        b4r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4r6ActionPerformed(evt);
            }
        });
        add(b4r6);
        b4r6.setBounds(662, 870, 60, 20);

        b4r6lainnya.setErrorlist(errorList);
        b4r6lainnya.setNextpage(true);
        b4r6lainnya.setPanel(this);
        b4r6lainnya.setPosition(34);
        b4r6lainnya.setVarName("b4r6lainnya");
        add(b4r6lainnya);
        b4r6lainnya.setBounds(500, 960, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SourceOfPicture/2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 794, 1070);
    }// </editor-fold>//GEN-END:initComponents

    private void b4r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4r6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.InputTextField b3r1;
    private View.InputTextField b3r2;
    private View.InputTextField b3r3;
    private View.InputTextField b3r4;
    private View.InputTextField b3r5;
    private View.InputTextField b3r6;
    private View.InputTextField b3r7;
    private View.InputTextField b3r8;
    private View.InputTextField b3r8lainnya;
    private View.InputTextField b4r1s1;
    private View.InputTextField b4r1s1lainnya;
    private View.InputTextField b4r1s2;
    private View.InputTextField b4r1s2lainnya;
    private View.InputTextField b4r2;
    private View.InputTextField b4r2lainnya;
    private View.InputTextField b4r3;
    private View.InputTextField b4r3lainnya;
    private View.InputTextField b4r4;
    private View.InputTextField b4r5;
    private View.InputTextField b4r5lainnya;
    private View.InputTextField b4r6;
    private View.InputTextField b4r6lainnya;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
