/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SectionPane;

import View.ErrorList;
import View.Panel;
import java.awt.KeyboardFocusManager;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JComponent;

/**
 *
 * @author ItsFadrur
 */
public class PanelUtama extends Panel {

    /**
     * Creates new form PanelUtama
     */
    
    private ErrorList errorList;
    
    public PanelUtama() {
        super();
        initComponents();
         KeyboardFocusManager.getCurrentKeyboardFocusManager()
                .addPropertyChangeListener("focusOwner",
                        new PropertyChangeListener() {

                            public void propertyChange(PropertyChangeEvent evt) {
                                if (!(evt.getNewValue() instanceof JComponent)) {
                                    return;
                                }
                                JComponent focused = (JComponent) evt.getNewValue();
                                if (isAncestorOf(focused)) {
                                    ((JComponent) focused.getParent()).scrollRectToVisible(focused.getBounds());
                                }
                            }
                        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        halaman11 = new View.SectionPane.Halaman1();
        jScrollPane2 = new javax.swing.JScrollPane();
        halaman21 = new View.SectionPane.Halaman2();
        jScrollPane3 = new javax.swing.JScrollPane();
        halaman31 = new View.SectionPane.Halaman3();
        jScrollPane4 = new javax.swing.JScrollPane();
        halaman41 = new View.SectionPane.Halaman4();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(halaman11);

        jPanel1.add(jScrollPane1, "card3");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(halaman21);

        jPanel1.add(jScrollPane2, "card3");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(halaman31);

        jPanel1.add(jScrollPane3, "card4");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportView(halaman41);

        jPanel1.add(jScrollPane4, "card5");

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.SectionPane.Halaman1 halaman11;
    private View.SectionPane.Halaman2 halaman21;
    private View.SectionPane.Halaman3 halaman31;
    private View.SectionPane.Halaman4 halaman41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        addHal("hal1", halaman11);
        addHal("hal1", halaman21);
        addHal("hal1", halaman31);
        addHal("hal1", halaman41);
        halaman11.setParent(this);
        halaman21.setParent(this);
        halaman31.setParent(this);
        halaman41.setParent(this);
        halaman11.setErrorList(errorList);
        halaman21.setErrorList(errorList);
        halaman31.setErrorList(errorList);
        halaman41.setErrorList(errorList);
        
    }

    public void setErrorList(ErrorList errorList) {
        this.errorList = errorList;
    }
}
