/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl55.kuesioner.SectionPane;

import pkl55.kuesioner.ErrorList;
import pkl55.kuesioner.Field;
import pkl55.kuesioner.Hal;
import java.awt.Component;

/**
 *
 * @author ItsFadrur
 */
public class Section2 extends Hal {

    public Section2() {
        initComponents();
    }
    
    public void addToView(){
        for (Component comp : getComponents()) {
            if (comp.isVisible()) {
                if (comp instanceof Field) {
                    ((Field) comp).addToView();
                    ((Field) comp).setErrorlist(errorList);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3ar1 = new pkl55.kuesioner.InputTextField();
        b3ar2 = new pkl55.kuesioner.InputTextField();
        b3ar3 = new pkl55.kuesioner.InputTextField();
        b3ar4 = new pkl55.kuesioner.InputTextField();
        b3ar5 = new pkl55.kuesioner.InputTextField();
        b3ar6 = new pkl55.kuesioner.InputTextField();
        b3ar7s1 = new pkl55.kuesioner.InputTextField();
        b3ar7s2 = new pkl55.kuesioner.InputTextField();
        b3ar7s2lainnya = new pkl55.kuesioner.InputTextField();
        b3ar7s3 = new pkl55.kuesioner.InputTextField();
        b3ar8s1 = new pkl55.kuesioner.InputTextField();
        b3ar8s2 = new pkl55.kuesioner.InputTextField();
        b3ar8s3 = new pkl55.kuesioner.InputTextField();
        b3ar8s4 = new pkl55.kuesioner.InputTextField();
        b3ar9s1 = new pkl55.kuesioner.InputTextField();
        b3ar9s2 = new pkl55.kuesioner.InputTextField();
        b3ar10s1 = new pkl55.kuesioner.InputTextField();
        b3ar10s2 = new pkl55.kuesioner.InputTextField();
        b3br11 = new pkl55.kuesioner.InputTextField();
        b3br12 = new pkl55.kuesioner.InputTextField();
        b3br13 = new pkl55.kuesioner.InputTextField();
        b3br14 = new pkl55.kuesioner.InputTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b3ar1.setErrorlist(errorList);
        b3ar1.setPanel(this);
        b3ar1.setPosition(20);
        b3ar1.setVarName("b3ar1");
        add(b3ar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 30, -1));

        b3ar2.setErrorlist(errorList);
        b3ar2.setPanel(this);
        b3ar2.setPosition(21);
        b3ar2.setVarName("b3ar2");
        add(b3ar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 30, -1));

        b3ar3.setErrorlist(errorList);
        b3ar3.setPanel(this);
        b3ar3.setPosition(22);
        b3ar3.setVarName("b3ar3");
        add(b3ar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 30, -1));

        b3ar4.setErrorlist(errorList);
        b3ar4.setPanel(this);
        b3ar4.setPosition(23);
        b3ar4.setVarName("b3ar4");
        add(b3ar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 30, -1));

        b3ar5.setErrorlist(errorList);
        b3ar5.setPanel(this);
        b3ar5.setPosition(24);
        b3ar5.setVarName("b3ar5");
        add(b3ar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 30, -1));

        b3ar6.setErrorlist(errorList);
        b3ar6.setPanel(this);
        b3ar6.setPosition(25);
        b3ar6.setVarName("b3ar6");
        add(b3ar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 30, -1));

        b3ar7s1.setErrorlist(errorList);
        b3ar7s1.setPanel(this);
        b3ar7s1.setPosition(26);
        b3ar7s1.setVarName("b3ar7s1");
        add(b3ar7s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 30, -1));

        b3ar7s2.setErrorlist(errorList);
        b3ar7s2.setPanel(this);
        b3ar7s2.setPosition(27);
        b3ar7s2.setVarName("b3ar7s2");
        add(b3ar7s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 690, 30, -1));

        b3ar7s2lainnya.setErrorlist(errorList);
        b3ar7s2lainnya.setPanel(this);
        b3ar7s2lainnya.setPosition(28);
        b3ar7s2lainnya.setVarName("b3ar7s2lainnya");
        add(b3ar7s2lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 741, 66, 18));

        b3ar7s3.setErrorlist(errorList);
        b3ar7s3.setPanel(this);
        b3ar7s3.setPosition(29);
        b3ar7s3.setVarName("b3ar7s3");
        add(b3ar7s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 810, 30, -1));

        b3ar8s1.setErrorlist(errorList);
        b3ar8s1.setPanel(this);
        b3ar8s1.setPosition(30);
        b3ar8s1.setVarName("b3ar8s1");
        add(b3ar8s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 870, 30, -1));

        b3ar8s2.setErrorlist(errorList);
        b3ar8s2.setFocusCycleRoot(true);
        b3ar8s2.setPanel(this);
        b3ar8s2.setPosition(31);
        b3ar8s2.setVarName("b3ar8s2");
        add(b3ar8s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 30, -1));

        b3ar8s3.setErrorlist(errorList);
        b3ar8s3.setPanel(this);
        b3ar8s3.setPosition(32);
        b3ar8s3.setVarName("b3ar8s3");
        add(b3ar8s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 30, -1));

        b3ar8s4.setErrorlist(errorList);
        b3ar8s4.setPanel(this);
        b3ar8s4.setPosition(33);
        b3ar8s4.setVarName("b3ar8s4");
        add(b3ar8s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 183, 30, -1));

        b3ar9s1.setErrorlist(errorList);
        b3ar9s1.setPanel(this);
        b3ar9s1.setPosition(34);
        b3ar9s1.setVarName("b3ar9s1");
        add(b3ar9s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 30, -1));

        b3ar9s2.setErrorlist(errorList);
        b3ar9s2.setPanel(this);
        b3ar9s2.setPosition(35);
        b3ar9s2.setVarName("b3ar9s2");
        add(b3ar9s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 30, -1));

        b3ar10s1.setErrorlist(errorList);
        b3ar10s1.setPanel(this);
        b3ar10s1.setPosition(36);
        b3ar10s1.setVarName("b3ar10s1");
        add(b3ar10s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 30, -1));

        b3ar10s2.setErrorlist(errorList);
        b3ar10s2.setPanel(this);
        b3ar10s2.setPosition(37);
        b3ar10s2.setVarName("b3ar10s2");
        add(b3ar10s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 30, -1));

        b3br11.setErrorlist(errorList);
        b3br11.setPanel(this);
        b3br11.setPosition(38);
        b3br11.setVarName("b3br11");
        add(b3br11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 30, -1));

        b3br12.setErrorlist(errorList);
        b3br12.setPanel(this);
        b3br12.setPosition(39);
        b3br12.setVarName("b3br12");
        b3br12.setVerifyInputWhenFocusTarget(false);
        add(b3br12, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 718, 70, -1));

        b3br13.setErrorlist(errorList);
        b3br13.setPanel(this);
        b3br13.setPosition(40);
        b3br13.setVarName("b3br13");
        add(b3br13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 808, 30, -1));

        b3br14.setErrorlist(errorList);
        b3br14.setPanel(this);
        b3br14.setNextpage(true);
        b3br14.setPosition(41);
        b3br14.setVarName("b3br14");
        add(b3br14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 870, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/SourceOfPicture/2.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl55.kuesioner.InputTextField b3ar1;
    private pkl55.kuesioner.InputTextField b3ar10s1;
    private pkl55.kuesioner.InputTextField b3ar10s2;
    private pkl55.kuesioner.InputTextField b3ar2;
    private pkl55.kuesioner.InputTextField b3ar3;
    private pkl55.kuesioner.InputTextField b3ar4;
    private pkl55.kuesioner.InputTextField b3ar5;
    private pkl55.kuesioner.InputTextField b3ar6;
    private pkl55.kuesioner.InputTextField b3ar7s1;
    private pkl55.kuesioner.InputTextField b3ar7s2;
    private pkl55.kuesioner.InputTextField b3ar7s2lainnya;
    private pkl55.kuesioner.InputTextField b3ar7s3;
    private pkl55.kuesioner.InputTextField b3ar8s1;
    private pkl55.kuesioner.InputTextField b3ar8s2;
    private pkl55.kuesioner.InputTextField b3ar8s3;
    private pkl55.kuesioner.InputTextField b3ar8s4;
    private pkl55.kuesioner.InputTextField b3ar9s1;
    private pkl55.kuesioner.InputTextField b3ar9s2;
    private pkl55.kuesioner.InputTextField b3br11;
    private pkl55.kuesioner.InputTextField b3br12;
    private pkl55.kuesioner.InputTextField b3br13;
    private pkl55.kuesioner.InputTextField b3br14;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
